[Refactor] #95 DateFormatterFactory 구현
YAPP-Github/24th-App-Team-3-iOS pull request #111
Opened 2024-08-04 16:39 UTC by dlrjswns

## Describe

- 서버를 통해 받아온 날짜관련 문자열처리를 효율적으로 작업하기위한 `DateFormatterFactory`구현

## Works made

- `Date`타입 관련 포맷팅을 `DateFormatterFactory`내부에서 작업하여 손쉽게 원하는 포맷의 날짜 문자열로 변환할 수 있도록 구현
- 프로젝트상 사용하는 날짜타입에 대한 `Locale`에 하나에만 국한되지않아 `SPLocale`열거형을 이용해 `DateFormatter`생성

## Changes Made

### As-Is

**기존 로직**
``` swift
let dateFormatter = DateFormatter() 
dateFormatter.dateFormat = "yyyy.MM.d"
dateFormatter.locale = Locale(identifier: "en_US")
dateFormatter.string(from: model.performanceTime ?? Date())
```
- 기존에는 원하는 포맷팅에 맞춰 일일이 구현해준 이후 `.string(from:)`을 이용해 변환 후 작업

**스크린샷**
<img src="" width="25%" alt="Image">

### To-BE

**변경 로직**
``` swift
let performanceTime = DateFormatterFactory.dateWithDot.string(from: performanceTime ?? Date())
```
- 미리 작성된 `DateFormatterFactory`의 포맷형식을 꺼내어 원하는 형태의 날짜 문자열로 변환하여 사용

**스크린샷**
<img src="https://github.com/user-attachments/assets/e7dd0921-fb44-4624-8afa-d1dad3489474" width="25%" alt="Image">
<img src="https://github.com/user-attachments/assets/1aaf4ac8-38ac-4f11-9a6c-1677090d8029" width="25%" alt="Image">

## How to Test

``` swift
let currentDate = Date()
let dateToString = DateFormatterFactory.dateWithDot.string(from: currentDate) // 2024.08.5
DateFormatterFactory.dateWithDot.date(from: dateToString) 
```
- `DateFormatterFactory`내부에 원하는 포맷형식을 지정해준 이후 위 코드와 같이 `.string(from:)`혹은 `date(from:)`을 통해서 변환하여 사용

## Issues Resolved

- #95 

## Additional context

- 부가적으로 `ReusableCell`채택하면 굳이 따로 identifier를 만들지않아도 되는거같아서 기존 식별자코드 대신 `reuseidentifier`로 대체하였습니다
- 현재 `DateFormatter`형식중 `"MM.dd(EEE) HH:mm"`(쇼팟 공연날짜에 관련된 포맷팅)을 사용할때에 `06.10(MON) 19:00`가 아닌 `06.10(Mon) 19:00`으로 나오고있는데 요일관련하여 전부 대문자로 변환하는 형식이 없는거같아 따로 `replacingOccurrences` 혹은 `uppercased`를 이용해 변환하여 작업해야할꺼같습니다

2024-08-04 19:00 UTC, ChoiysApple requested changes
Cell 부분에 옵셔널 처리 부분만 수정하시면 될거 같네요

`추가`
1. `ReusableCell` 수정은 원칙적으로는 별개의 PR이 맞지만, 커밋도 잘 분리하셨고 컨플릭 우려도 없어 여기서 머지할게요
2. `DateFormatterFactory`가 특정 상황에 맞는 날짜 string을 완성된 형태로 반환해 주는 형식인것 같은데, 그렇다면 `dateWithTicketing.string(:Date)`로 스트링을 받아서 별도 uppercase 처리를 안하는게 이상적인거 같긴 하지만, 현재 구조를 갈아 엎어야 하기 때문에 View단에서 처리해주는 걸로 가시죠

2024-08-04 19:35 UTC, dlrjswns commented
> Cell 부분에 옵셔널 처리 부분만 수정하시면 될거 같네요
> 
> `추가`
> 
> 1. `ReusableCell` 수정은 원칙적으로는 별개의 PR이 맞지만, 커밋도 잘 분리하셨고 컨플릭 우려도 없어 여기서 머지할게요
> 2. `DateFormatterFactory`가 특정 상황에 맞는 날짜 string을 완성된 형태로 반환해 주는 형식인것 같은데, 그렇다면 `dateWithTicketing.string(:Date)`로 스트링을 받아서 별도 uppercase 처리를 안하는게 이상적인거 같긴 하지만, 현재 구조를 갈아 엎어야 하기 때문에 View단에서 처리해주는 걸로 가시죠

네 알겠습니다, uppercase건은 최대한 한번 고민해볼게요 저도 DateFormatterFactory에서 이쁘게 내려주는게 이상적인거같은데 🧐🧐

2024-08-04 19:36 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/PerformanceStateView.swift
> +            let performanceDate = DateFormatterFactory.dateWithPerformance.string(from: performanceDate)
아 바로 수정하도록 하겠습니다

2024-08-05 10:46 UTC, ChoiysApple approved these changes
건준님 수고하셨습니다. 다만 커밋 이름은 수정이 필요해보여요

1. `#95 ReusableCell사용하고있는 식별자 코드 수정` 
-> 이 작업은 #95 작업과 무관한 작업이니 #0으로 바꿔주세요

2. `#95 PR리뷰 반영`
-> 이 커밋은 나중에 봤을떄 어떤 작업인지 한눈에 알기 어렵습니다. 실제 작업 내용을 기반으로 제목 작성해주세요

이 두개 커밋 타이틀만 수정하고 머지해주세요

2024-08-05 11:01 UTC, merged