[Feature] #109 바텀시트 개발
YAPP-Github/24th-App-Team-3-iOS pull request #116
Opened 2024-08-05 14:12 UTC by ChoiysApple

## Describe

- 바텀시트 관련 기능 추가

## Works made

- 기본 바텀시트 개발 `BottomSheetViewController`
- 커스텀 바텀시트 개발 `SPDefaultBottomSheetViewController`
- 공용 바텀시트 extension 개발 `BaseViewController+BottomSheet`

## Changes Made

### To-BE

**변경 로직**
```swift
let loginBottomSheet = SPDefaultBottomSheetViewController(
        message: Strings.bottomSheetLoginMessage,
        buttonTitle: Strings.bottomSheetLoginButtonTitle
    )

self.presentBottomSheet(viewController: loginBottomSheet)
```

**스크린샷**
<img src="https://github.com/user-attachments/assets/3a9506d4-68d4-4607-926b-85c910d7a6b5" width="25%" alt="Image">

## How to Test
- `BaseViewController` 에서 `showLoginBottomSheet()` 코드 추가

## Issues Resolved
- close #109 

## Additional context

- 다른 바텀시트 개발 필요

## References

- [Transform: CGAffineTransform](https://www.hackingwithswift.com/read/15/4/transform-cgaffinetransform)
- [Bottom Sheet View Controller with Dynamic Content Height in iOS](https://levelup.gitconnected.com/bottom-sheet-view-controller-with-dynamic-content-height-in-ios-4160222f738)

2024-08-05 17:27 UTC, dlrjswns requested changes
<img src="https://github.com/user-attachments/assets/87706aa5-289d-4fd8-a95c-1e7a8b88e987" width="25%" alt="Image">

@ChoiysApple 
대건님 이거 스와이프하다가 중간에 먹힐때가 있는거같아요

확인해보니 grabber잡고 아래로내리다가 확 올리면 멈추는거같아요

2024-08-05 17:27 UTC, dlrjswns commented on ShowPot/ShowPot/Common/UI/SPDefaultBottomSheetViewController.swift
> +    }
```suggestion
    lazy var bottomButton = SPButton(.accentBottomEnabled).then { button in
        button.setText(buttonTitle)
        button.configuration?.background.cornerRadius = 2
    }
```
- bottomButton에 cornerRadius값을 2로 수정해야할꺼같아요

2024-08-05 17:27 UTC, dlrjswns commented on ShowPot/ShowPot/Common/UI/SPDefaultBottomSheetViewController.swift
> +    }
<img width="386" alt="스크린샷 2024-08-06 오전 2 17 09" src="https://github.com/user-attachments/assets/dc91dde2-9bae-4359-a991-5cef759a3481">

대건님 피그마 좌우 Inset값이 상이한거같아요, 코드보니까 `SPDefaultBottomSheetViewController`하고 `BottomSheetViewController` 둘다 좌우 Inset이 있어서 그런거같아요

2024-08-06 01:47 UTC, ChoiysApple commented
> <img src="https://github.com/user-attachments/assets/87706aa5-289d-4fd8-a95c-1e7a8b88e987" width="25%" alt="Image">
> 
> 
> 
> @ChoiysApple 
> 
> 대건님 이거 스와이프하다가 중간에 먹힐때가 있는거같아요
> 
> 
> 
> 확인해보니 grabber잡고 아래로내리다가 확 올리면 멈추는거같아요

저렇게 멈춰있는 상태에서 버튼이나 빈화면 클릭하면 어떻게되나요?

2024-08-06 04:00 UTC, dlrjswns commented
> > <img alt="Image" width="25%" src="https://private-user-images.githubusercontent.com/39263235/355190046-87706aa5-289d-4fd8-a95c-1e7a8b88e987.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MTcwNjgsIm5iZiI6MTcyMjkxNjc2OCwicGF0aCI6Ii8zOTI2MzIzNS8zNTUxOTAwNDYtODc3MDZhYTUtMjg5ZC00ZmQ4LWE5NWMtMWU3YThiODhlOTg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDAzNTkyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlMTU5MDZmM2YyMGY5OGQ5NWI5MzM1NjAyNTk3MmU2OTE2ZmY2MTYyYTBjMTk2MDJiZjZiNmY2N2EwZTYxOTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iEzoLVkJ0ev27w51ugrOkdx9H2W3U9VcX2TKKedFmJM">
> > @ChoiysApple
> > 대건님 이거 스와이프하다가 중간에 먹힐때가 있는거같아요
> > 확인해보니 grabber잡고 아래로내리다가 확 올리면 멈추는거같아요
> 
> 저렇게 멈춰있는 상태에서 버튼이나 빈화면 클릭하면 어떻게되나요?

@ChoiysApple 
방금 확인해보니 빈화면클릭하면 바텀시트 사라지고 로그인버튼을 클릭하면 바텀시트가 끊기면서 원상복구되더니 로그인화면으로 이동해요 !!

2024-08-06 11:58 UTC, ChoiysApple commented on ShowPot/ShowPot/Common/UI/SPDefaultBottomSheetViewController.swift
> +    }
이부분은 `SPButton.accentBottomEnabled`에 지정된 스타일을 수정해야 하는 부분입니다.
다른 지정 스타일에도 cornerRadius 빠져있어서 추가했습니다

2024-08-06 11:59 UTC, ChoiysApple commented on ShowPot/ShowPot/Common/UI/SPDefaultBottomSheetViewController.swift
> +    }
수정 완료 (`BottomSheetViewController`에서 상/하 inset만 정해주도록 수정)

2024-08-06 12:00 UTC, ChoiysApple commented
이 이슈는 재현되기도 까다롭고, 앱을 먹통시키는 정도는 아닌데 고치는데는 시간이 좀 오래 걸릴거 같아서
`Known issue`로 등록해놓고 나중에 고치는걸로 할게요

2024-08-06 12:01 UTC, merged

2024-08-06 12:01 UTC, ChoiysApple commented
@dlrjswns 
수정해서 머지했습니다. 기존 PR rebase 진행해주세요