[Feature] #107 내공연알림설정화면 UI 구현
YAPP-Github/24th-App-Team-3-iOS pull request #121
Opened 2024-08-09 13:06 UTC by dlrjswns

## Describe

- 내 공연 알림설정에 관련된 UI를 구현

## Works made

- 내 공연에 대한 리스트를 `NSDiffableDataSource`를 이용해 구현 
- 알림 변경/해제를 위한 바텀시트 구현
- 알림 변경 시 이전알림정보와 변경하고자하는 알림정보와 상이한지에 따른 활성화/비활성화 버튼 구현
- 알림 변경 버튼 클릭 시 미선택/선택에 대한 레이아웃 변경 추가 
- 내 공연리스트 유무에 따른 `MyPerformanceEmptyView`구현
- 티켓팅시간정보는 서버쪽에서 내려보내주기에 `MyAlarmListViewModel`내부에서 관리할 수 있도록 구현
- 티켓팅시간 업데이트에 대한 API가 구현되지않아 변경하고자하는 공연모델자체를 `TicketingAlarmViewModel`의 초기화함수를 통해 받고있음 -> 이후 `showID`로 수정
- `UIButton+Extension`파일에 `Configuration updateHandler`를 이용한 활성화/비활성화 버튼 구현

## Changes Made

### As-Is

**기존 로직**
- 기존 내공연알림설정화면에 대한 로직 없음

**스크린샷**
- 기존 내공연알림설정화면에 대한 로직 없음

### To-BE

**변경 로직**
- 기존 내공연알림설정화면에 대한 로직 없음

**스크린샷**
<img src="https://github.com/user-attachments/assets/603d56c4-7b5d-4bc4-97fb-341b94cb9cca" width="25%" alt="Image"><img src="https://github.com/user-attachments/assets/b32f7b20-6945-4db6-a00b-d4823bb05983" width="25%" alt="Image"><img src="https://github.com/user-attachments/assets/902a3c20-78a5-4ef8-9b12-63d0b3320c44" width="25%" alt="Image">

**동작영상**
https://github.com/user-attachments/assets/5d33058f-5133-4474-b324-a8cfd8fa7847

## How to Test

- 내 공연알림설정 바텀시트에 대한 동작방식을 확인합니다
- `MyAlarmListViewModel`의 티켓팅시간 상태값을 변경하여 올바르게 동작하는지 확인합니다

## Issues Resolved

- #107 

## Additional context

![Simulator Screen Recording - iPhone 15 Pro Max - 2024-08-09 at 22 02 00](https://github.com/user-attachments/assets/dfb4c5a5-bad8-4e15-bbbb-55fee5746986)
``` swift
private let alarmSettingButton = SPButton(fontType: KRFont.H2).then {
        $0.configurationUpdateHandler = $0.configuration?.spButton(label: Strings.myPerformanceTicketButtonTitle)
}
output.isEnabledBottomButton
        .drive(alarmSettingButton.rx.isEnabled)
        .disposed(by: disposeBag)
```
- UIButton+Extension에 UIButton Configuration의 updateHandler를 이용해 상태값만을 가지고 레이아웃을 업데이트하는 로직이 추가되었습니다, 확인해보시고 궁금한점 말해주세요 !
- 해당 부분은 내공연알림설정화면에 사용은 됐지만 부가적으로 만든 느낌이라서 Additional context에 추가합니다 
- 상단에 띄어진 부분은 `navigationBar`부분인데 이후 `SaveViewController`를 이용해 `push`하면 자연스럽게 올라가는 부분입니다

2024-08-10 17:05 UTC, ChoiysApple requested changes
몇가지 추가 개발 필요건들이 있습니다
1. 알람 시간 변경하기 버튼 클릭시, 바텀시트가 내려가야 하는 동작이 구현 안되었습니다.
2. 공연 Cell 클릭시 상세 정보로 이동해야 할 것 같습니다. 로그 추가해주세요
3. 알람 해제시 `알림 해제하기 인덱스: 4` 처럼 인덱스 정보만 로그에 표출됩니다. 인덱스에 해당하는 데이터 자체를 로그 찍어주세요
4. 파일을 상당히 많이 추가하셨는데, 폴더링이 하나도 안되어있습니다. 보기 좋게 정리해주세요. ( 추가로 다른 부분에서도 사용되어야 하는 뷰는 Common 폴더에 위치해야 합니다)

지금 서버 없이 개발하고 있기 때문에, 서버기능이 추가되었을때 usecase 수정 만으로 화면이 완벽하게 동작하도록 개발 완료되어야 합니다.


## usecase를 제외한 부분에는 추가 작업 필요 없을 정도로 개발해주세요
감이 안오신다면, 제가 올려둔 `장르 구독 화면` 작업 참고해주세요

2024-08-10 17:05 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Saved/MyPerformanceAlarm/CustomView/TicketingAlarmCell.swift
> +}
서버에서 시간 경과로 선택 불가능하게 되는 데이터는 넘겨주지 않아요
티켓팅 시간 데이터를 기반으로 체크박스 비활성화 여부를 판단하고 반영하는 로직 개발해주세요

2024-08-10 17:26 UTC, dlrjswns commented on ShowPot/ShowPot/Common/Extension/UIButton+Extension.swift
> +extension UIBackgroundConfiguration: Then { }
@ChoiysApple 
아 기존에 style.background를 일일이 접근해서 cornerRadius와 backgroundColor를 지정해주었는데 이를 마치 Then처럼 with를 이용해서 한번에 접근하기 쉽게하기위해 선언하였어요 !!

지금은 대건님 코멘트주신것처럼 `SPButtonStyle`로 수정돼어 해당 코드를 지울꺼같습니다 !

2024-08-10 17:27 UTC, dlrjswns commented on ShowPot/ShowPot/Common/Extension/UIButton+Extension.swift
> +    }
현재 SPButtonStyle로 수정돼 삭제처리하였습니다

2024-08-10 17:30 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Tab/Saved/MyPerformanceAlarm/CustomView/TicketingAlarmBottomSheetViewModel.swift
> +    }
`NSDiffableDataSource`를 사용할때에 snapshot을 생성해서 dataSource에 apply해주어야하는데 이때 반드시 섹션에 대한 정보 이후 아이템에 대한 정보를 방출해야하기때문에 이를 구분하기위해서 enum형을 사용해주었습니다

2024-08-10 17:33 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Tab/Saved/MyPerformanceAlarm/CustomView/TicketingAlarmBottomSheetViewModel.swift
> +    private let performanceModel: PerformanceInfoCollectionViewCellModel
@ChoiysApple 
아 이 부분을 만들어둔 이유가 티켓팅알림시간을 업데이트 이후 `알림 설정하기`버튼을 클릭했을때에 내가 어떤 공연에 대한 알림시간을 변경했는지 로그를 찍어주기위해서 초기화함수에 선언해주었어요

실제로 업데이트하는 API를 호출할때엔 `showID`가 필요하지만 현재 존재하지않아 해당 모델 자체를 받아오게 했어요

2024-08-10 17:43 UTC, dlrjswns commented on ShowPot/ShowPot/Common/UI/Base/BottomSheetViewController.swift
> +            }
@ChoiysApple 
혹시 didTapBottomButton으로 모달 2개를 연속적으로 표출하는걸 어떤식으로 해결할 수 있을까요 ??

2024-08-11 06:16 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Saved/MyPerformanceAlarm/CustomView/TicketingAlarmBottomSheetViewModel.swift
> +    private let performanceModel: PerformanceInfoCollectionViewCellModel
`PerformanceInfoCollectionViewCellModel`이라는건 네이밍부터가 `PerformanceInfoCollectionViewCell` 내부에 삽입될 데이터를 묶어주기 위해 생성한 모델이고, 그렇기 때문에 외부가 아닌 해당 `Cell`에 선언되어있어요

이런 모델을 공용으로 사용하고 싶다면 이런 방식이 아니라, 셀 외부에 공용으로 사용될 모델로 선언하고 사용되어야 합니다
당연히 네이밍에 `PerformanceInfoCollectionViewCell`은 빠져야 하구요.

실제로 해당 바텀시트를 내공연 알림설정 이외의 화면에서 사용해야 하기 때문에 수정 필요합니다.

2024-08-11 06:16 UTC, ChoiysApple commented on ShowPot/ShowPot/Common/UI/Base/BottomSheetViewController.swift
> +            }
> @ChoiysApple 혹시 didTapBottomButton으로 모달 2개를 연속적으로 표출하는걸 어떤식으로 해결할 수 있을까요 ??

didTapBottomButton이벤트 받았을때 현재 바텀시트 내리고

2024-08-11 08:27 UTC, dlrjswns commented on ShowPot/ShowPot/Common/UI/Base/BottomSheetViewController.swift
> +            }
@ChoiysApple 
`didTapBottomButton`이벤트가 `SPDefaultBottomSheetController`에 존재하는건데 저 completion을 동작하기위한 바텀시트는 레이아웃이 좀 달라서 `BottomSheetViewController`를 상속받아 개발된거라서 존재하지않아 물어본거였어요 !

2024-08-11 08:29 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Tab/Saved/MyPerformanceAlarm/CustomView/TicketingAlarmBottomSheetViewModel.swift
> +    private let performanceModel: PerformanceInfoCollectionViewCellModel
오오오 확실히 이해했어요 !! 좋습니다

2024-08-11 08:29 UTC, ChoiysApple commented on ShowPot/ShowPot/Common/UI/Base/BottomSheetViewController.swift
> +            }
> @ChoiysApple `didTapBottomButton`이벤트가 `SPDefaultBottomSheetController`에 존재하는건데 저 completion을 동작하기위한 바텀시트는 레이아웃이 좀 달라서 `BottomSheetViewController`를 상속받아 개발된거라서 존재하지않아 물어본거였어요 !

그럼 필요한 커스텀 바텀시트에 `didTapBottomButton`을 만들어서 `rx.tap`을 바인딩하거나 `#selecter`로 타켓 추가해서 클로저를 주입해주거나 해서 버튼 이벤트를 처리하면 되겠죠?

2024-08-11 08:30 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Saved/MyPerformanceAlarm/CustomView/TicketingAlarmCell.swift
> +}
@dlrjswns 
이거 서버에서 내려주는 걸로 결론났나요?

2024-08-11 18:30 UTC, ChoiysApple requested changes
약간 수정사항 있어서 약간만 수정해주세요~

2024-08-12 09:30 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Tab/Saved/MyShowAlarm/CustomView/BottomSheet/TicketingAlarmBottomSheetViewModel.swift
> +                // TODO: - 티켓팅 시간정보를 가지고 API를 호출 필요
맞습니다 !! 헌데 이 부분은 usecase에 현재 티켓팅시간정보를 넘겨주고있어 삭제해도 될꺼같아요 삭제하도록 할게요 !!

2024-08-12 09:32 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Tab/Saved/MyShowAlarm/MyShowAlarmCoordinator.swift
> +    }
@ChoiysApple 
아 지금 저 부분이 내 공연알림리스트정보가 없을때 EmptyView가 보여지는데 거기있는 버튼입니다, 
헌데 거기있는 `공연정보보러가기`버튼이 공연상세화면으로 이동할꺼같진않아 따로 두었어요 !!

이 부분은 디자이너한테 여쭤보고 동일하다면 수정하도록 할게요 !!

2024-08-12 09:56 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Tab/Saved/MyShowAlarm/CustomView/BottomSheet/TicketingAlarmBottomSheetViewModel.swift
> +                return false
@ChoiysApple 
지금 이 버튼활성화/비활성화 여부가 
1. `사용가능한 = isEnabled` 시간대를 기준으로 기존 알림정보와 변경된 알림정보가 `변경되었는지 = isChecked` 

위 기준이라서 filter를 이용해 확실히 이용가능한 시간만을 필터링하는게 낫다생각했어요, 이 부분을 zip이용해서 간략하게 바꿔볼게요 !!

2024-08-12 10:07 UTC, dlrjswns commented
@ChoiysApple 
공연정보보러가기버튼은 디자이너분께서 전체공연화면으로 이동한다하여 수정하였습니다 !

2024-08-12 11:58 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Saved/MyShowAlarm/CustomView/BottomSheet/TicketingAlarmBottomSheetViewModel.swift
> +                return false
이해 안되요
이부분이 알람 시간 설정 바텀시트에서, 기존 설정이랑 달라졌는지 판단하는 로직 아닌가요?

2024-08-12 11:59 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Saved/MyShowAlarm/MyShowAlarmCoordinator.swift
> +    }
기존에 개발된 이름은 "전체공연 보러가기" 입니다

피그마나 UX 라이팅에 사용되는 문구 확인없이 개발 네이밍이 그만 사용해주세요

2024-08-12 12:07 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Tab/Saved/MyShowAlarm/CustomView/BottomSheet/TicketingAlarmBottomSheetViewModel.swift
> +                return false
@ChoiysApple 
맞습니다 !! 근데 반드시 이용가능한 시간중에서 기존 설정이랑 달라졌는지 판단하는 로직이에요 !!

만약에 단순 map으로만 했을 시에 이용가능하지않은 티켓팅시간인데도 달라졌다는 이유만으로 버튼이 활성화되면 안되기때문에 
filter를 이용해서 이용가능한 시간만 거친거에요 !!

2024-08-12 12:10 UTC, dlrjswns commented on ShowPot/ShowPot/Resource/Localizable/Localizable.strings
> +"my_show_empty_button_title" = "공연 정보 보러가기";
@ChoiysApple 
대건님 여기에 `공연 정보 보러가기`라고 작성돼있는데 혹시 어떤 부분에 `전체공연 보러가기`라고 작성돼있었나요...?

2024-08-12 12:17 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Saved/MyShowAlarm/CustomView/BottomSheet/TicketingAlarmBottomSheetViewModel.swift
이건 왜 안옮겼어요

2024-08-12 12:17 UTC, ChoiysApple commented on ShowPot/ShowPot/Resource/Localizable/Localizable.strings
> +"my_show_empty_button_title" = "공연 정보 보러가기";
아뇨 동작이 전체공연 리스트로 이동하는 거잖아요

<img width="363" alt="image" src="https://github.com/user-attachments/assets/d59c1f5f-87a1-4ab9-bf2f-0036536178c8">


그리고 공연 정보라고 하면 이게
공연 상세정보인지 / 전체 공연 정보인지 / 필터링된 공연정보인지 뭔지 어떻게 구분해요
필요한 화면 만들어졌을때 바로 연결하려고 로깅처리하고 필요하면 `TODO` 달아주는건데 저러면 대체 무슨의미가있어요

2024-08-12 12:41 UTC, dlrjswns commented on ShowPot/ShowPot/Resource/Localizable/Localizable.strings
> +"my_show_empty_button_title" = "공연 정보 보러가기";
@ChoiysApple 
아 지금 저게 제가 민경님이랑 대화하고난 이후에 추가가 된 거였어요, 원래 기존에는 공연 정보 보러가기라는 버튼만 존재했던거라서 
저런식으로 공연정보에 대한 화면이 있다고 생각해 로그를 달아놨던거였어요

홈화면에 전체공연보러가기버튼이 있었지만 전체공연화면이 기존에 존재하지않았던것처럼요

2024-08-12 12:46 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Tab/Saved/MyShowAlarm/CustomView/BottomSheet/TicketingAlarmBottomSheetViewModel.swift
아 요것도 옮기도록 하겠습니다 !!

2024-08-13 12:31 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Saved/MyShowAlarm/MyShowAlarmCoordinator.swift
> +    }
> 요거 네이밍 변경건 뺴먹으셨어요
> 
> "공연 리스트 화면" 이나 "전체 공연 화면" 단어 이용해서 수정해주시고 시간 많이 지체되었으니, 수정 완료후 직접 머지해주세요

최신버전이 아니라, 리뷰 이전 버전으로 리뷰가 들어갔네요
머지할게요 수고하셨습니다

2024-08-13 12:31 UTC, merged