[Feature] #124 마이페이지 UI 구현
YAPP-Github/24th-App-Team-3-iOS pull request #130
Opened 2024-08-15 16:39 UTC by dlrjswns

## Describe

## Works made

- 마이페이지 관련 UI를 개발 
- 디자인 수정으로 인해 내 공연 메뉴 수정 
- 홈 화면 누락되었던 `hidesBottomBarWhenPushed` 삭제

## Changes Made

### As-Is

**기존 로직**
- 이전 마이페이지 화면 없음

**스크린샷**
- 이전 마이페이지 화면 없음

### To-BE

**변경 로직**
- 이전 마이페이지 화면 없음

**스크린샷**
<img src="https://github.com/user-attachments/assets/785df77e-a66c-49e9-9429-9295565ac2f4" width="25%" alt="Image"><img src="https://github.com/user-attachments/assets/5c19fa44-4f01-4a59-b2a8-87872a9d5ca4" width="25%" alt="Image">

## How to Test

- `마이페이지`화면 확인 
- `SettingViewModel`의 `nickname`을 수정하여 닉네임 존재 여부에 따른 알림텍스트 변경 확인 

## Issues Resolved

- #124 

## Additional context

- 디자인 변경으로 인해 기존 내 공연메인화면에 대한 메뉴 탭을 변경하였습니다, 그에 따라 SwiftGen 변경작업 진행하였고 추후 내 공연메인화면관련 PR로 `티켓팅종료화면`, `관심공연화면`개발하여 올리도록 할게요 
- 이전 PR에서 `hidesBottomBarWhenPushed`삭제한 코드가 누락되어 다음 PR에서 삭제하였습니다
- @ChoiysApple  현재 `setNavigationBarItem`을 이용하고있는데 Inset값이 상이해서 이 부분 고쳐야할꺼같아요 

## References

2024-08-15 20:01 UTC, dlrjswns commented
@ChoiysApple 
<img src="https://github.com/user-attachments/assets/0bb910da-f7c0-411e-b429-b7354a9b6e49" width="25%" alt="Image">
대건님 제가 UseCase모델에 대해서 곰곰히 생각을 해보았는데 저희가 위 이미지같은 화면이 많잖아요, 해당 화면의 비즈니스 로직이라 한다면 특정 셀을 선택했을때 `id`를 가지고 조회하거나 삭제하는 로직인데 `ShowSummary`라는 모델을 만들어서 이미지와 비슷한 화면에 공통으로 사용하는건 좋은 아이디어같나요 ?? (마지막 커밋에 수정해보았는데 확인부탁드려요)

그리고 부가적으로 `ShowData`라는 표현을 내공연메인화면PR에서 사용하는데 이 부분을 `Show`라고 정정하는건 어떠신지 의견이 궁금해요 !!
괜찮으시면 이 부분은 - #125 여기다가 추가해놓을게요 !!

2024-08-16 09:15 UTC, ChoiysApple commented
> 대건님 제가 UseCase모델에 대해서 곰곰히 생각을 해보았는데 저희가 위 이미지같은 화면이 많잖아요, 해당 화면의 비즈니스 로직이라 한다면 특정 셀을 선택했을때 `id`를 가지고 조회하거나 삭제하는 로직인데 `ShowSummary`라는 모델을 만들어서 이미지와 비슷한 화면에 공통으로 사용하는건 좋은 아이디어같나요 ?? (마지막 커밋에 수정해보았는데 확인부탁드려요)

이전에도 지금 비슷한 Cell 여러개 생기는 문제에 대해서, View 계층만 분리해서 가지고 있으면 된다 or 가장 베이스가 되는 Cell 만들어서 사용하면 된다 라고 설명드렸던게 지금 말씀하신 방법이랑 비슷한 방향입니다. 다만 지금 상황에서 일부만 수정하게 되면, 수정되어야 하는 부분이 누락될 위험이 너무 높아서 그냥 두고 있는거라 일단 작업하신 부분만 반영해 두면 될거같습니다

> 그리고 부가적으로 `ShowData`라는 표현을 내공연메인화면PR에서 사용하는데 이 부분을 `Show`라고 정정하는건 어떠신지 의견이 궁금해요 !! 괜찮으시면 이 부분은 - #125 여기다가 추가해놓을게요 !!

`내공연메인화면PR` 이라고만 하시면 어디 부분인지 몰라요. 해당 PR은 바뀐 파일만 31개입니다. 직접 가서 찾아보는건 시간 소요가 커서 설명을 잘 해주세요

2024-08-16 09:31 UTC, ChoiysApple requested changes
로그인 텍스트 눌렀을 때 로그인 모달뷰 뜨는거 개발 안됬어요

2024-08-16 09:31 UTC, ChoiysApple commented on ShowPot/ShowPot/Data/UserDefaults/UserDefaultsKey.swift
> +
유저 관련된 데이터 (token, 이름 등등) 은 나중에 별도 객체로 관리할 계획이긴 해요
알고만 계셔요

2024-08-16 09:31 UTC, ChoiysApple commented on ShowPot/ShowPot/Resource/Localizable/Localizable.strings
> +"my_page_menu_button_3" = "구독한 장르";
버튼 순서를 이용해서 네이밍 해주신거 같은데, 여긴 클린 아키텍쳐 계층으로 따지면 가장 낮은 수준의 계층입니다. 순수한 데이터가 뷰 계층을 알고 있으면 안되죠

2024-08-16 09:31 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Settings/CustomView/MyPageHeaderView.swift
> +}
여기 부분은 extension에 들어가는게 맞을거 같네요

2024-08-16 09:31 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Settings/SettingsViewController.swift
> +        setNavigationBarItem(title: Strings.myPageNavigationTitle, rightIcon: .icSetting.withTintColor(.gray400)) // FIXME: - title, rightIcon만 존재하는 경우 inset값 수정 필요
이건 bugfix로 이슈 하나 만들고 저 할당해주세요

2024-08-16 10:14 UTC, dlrjswns commented
> > 대건님 제가 UseCase모델에 대해서 곰곰히 생각을 해보았는데 저희가 위 이미지같은 화면이 많잖아요, 해당 화면의 비즈니스 로직이라 한다면 특정 셀을 선택했을때 `id`를 가지고 조회하거나 삭제하는 로직인데 `ShowSummary`라는 모델을 만들어서 이미지와 비슷한 화면에 공통으로 사용하는건 좋은 아이디어같나요 ?? (마지막 커밋에 수정해보았는데 확인부탁드려요)
> 
> 이전에도 지금 비슷한 Cell 여러개 생기는 문제에 대해서, View 계층만 분리해서 가지고 있으면 된다 or 가장 베이스가 되는 Cell 만들어서 사용하면 된다 라고 설명드렸던게 지금 말씀하신 방법이랑 비슷한 방향입니다. 다만 지금 상황에서 일부만 수정하게 되면, 수정되어야 하는 부분이 누락될 위험이 너무 높아서 그냥 두고 있는거라 일단 작업하신 부분만 반영해 두면 될거같습니다
> 
> > 그리고 부가적으로 `ShowData`라는 표현을 내공연메인화면PR에서 사용하는데 이 부분을 `Show`라고 정정하는건 어떠신지 의견이 궁금해요 !! 괜찮으시면 이 부분은 - #125 여기다가 추가해놓을게요 !!
> 
> `내공연메인화면PR` 이라고만 하시면 어디 부분인지 몰라요. 해당 PR은 바뀐 파일만 31개입니다. 직접 가서 찾아보는건 시간 소요가 커서 설명을 잘 해주세요

아 좋은 말씀감사해요 👍👍👍 해당 PR에 멘션두도록 하겠습니다 !!

2024-08-16 10:23 UTC, dlrjswns commented on ShowPot/ShowPot/Resource/Localizable/Localizable.strings
> +"my_page_menu_button_3" = "구독한 장르";
@ChoiysApple 
"my_page_subscribe_artist_button_title" 이런식으로 수정하도록 하겠습니다 !

2024-08-16 10:26 UTC, dlrjswns commented
> 1. 로그인 텍스트 눌렀을 때 로그인 모달뷰 뜨는거 개발 안되어있습니다.
> 2. "로그인 후 다채로운 내한공연을 만나보세요." 텍스트 부분 행간이 좁아보이는데 확인해주세요. `SPLabel`의 기본값은 `numberOfLines = 1`이고, 이 상태에서는 행간이 적용되지 않습니다

@ChoiysApple 
1. 아 지금 보니 피그마에 comment로 언급됐군요 ? 확인했습니다 !!
2. 이 부분은 현재 `SPLabel`을 사용하기 힘들어보여서 `NSAttributedString+Extension`의 함수를 이용해보도록 하겠습니다 !!

2024-08-16 12:39 UTC, ChoiysApple commented
> > 1. 로그인 텍스트 눌렀을 때 로그인 모달뷰 뜨는거 개발 안되어있습니다.
> 
> > 2. "로그인 후 다채로운 내한공연을 만나보세요." 텍스트 부분 행간이 좁아보이는데 확인해주세요. `SPLabel`의 기본값은 `numberOfLines = 1`이고, 이 상태에서는 행간이 적용되지 않습니다
> 
> 
> 
> @ChoiysApple 
> 
> 1. 아 지금 보니 피그마에 comment로 언급됐군요 ? 확인했습니다 !!
> 
> 2. 이 부분은 현재 `SPLabel`을 사용하기 힘들어보여서 `NSAttributedString+Extension`의 함수를 이용해보도록 하겠습니다 !!

2번 문제 원인이 뭔가요? 원인이 뭔데 SPLabel 사용이 불가한가요?

2024-08-16 13:28 UTC, dlrjswns commented
> > > 1. 로그인 텍스트 눌렀을 때 로그인 모달뷰 뜨는거 개발 안되어있습니다.
> > 
> > 
> > > 2. "로그인 후 다채로운 내한공연을 만나보세요." 텍스트 부분 행간이 좁아보이는데 확인해주세요. `SPLabel`의 기본값은 `numberOfLines = 1`이고, 이 상태에서는 행간이 적용되지 않습니다
> > 
> > 
> > @ChoiysApple
> > 
> > 1. 아 지금 보니 피그마에 comment로 언급됐군요 ? 확인했습니다 !!
> > 2. 이 부분은 현재 `SPLabel`을 사용하기 힘들어보여서 `NSAttributedString+Extension`의 함수를 이용해보도록 하겠습니다 !!
> 
> 2번 문제 원인이 뭔가요? 원인이 뭔데 SPLabel 사용이 불가한가요?

기존에 `로그인`텍스트부분의 터치이벤트를 주려면 attribute에 link를 적용해야하는데 UITextView의 Delegate를 사용해야해서 SPLabel이 힘들다 판단했어요 !!

2024-08-17 05:31 UTC, ChoiysApple approved these changes

2024-08-17 07:02 UTC, merged