[Feature] #131 티켓팅종료 및 관심공연 UI 구현
YAPP-Github/24th-App-Team-3-iOS pull request #134
Opened 2024-08-17 17:05 UTC by dlrjswns

## Describe

- `티켓팅종료`, `관심공연`화면 UI 작성

## Works made

- `티켓팅종료`, `관심공연`관련 데이터 유무에 따른 `EmptyView` hidden 로직 추가
- `관심공연`화면 삭제버튼에 따른 애니메이션 추가

## Changes Made

### As-Is

**기존 로직**
- 기존 화면 로직 없음

**스크린샷**
- 기존 화면 로직 없음

### To-BE

**변경 로직**
- 기존 화면 로직 없음

**스크린샷**
<img src="https://github.com/user-attachments/assets/afbe4a48-d1c9-4131-9cfb-d696c58b8711" width="25%" alt="Image"><img src="https://github.com/user-attachments/assets/f19e06cb-61e1-40bb-9e92-1af0889d417c" width="25%" alt="Image"><img src="https://github.com/user-attachments/assets/28917495-2490-49aa-a37c-98b88c993c36" width="25%" alt="Image"><img src="https://github.com/user-attachments/assets/c979b6b8-ff82-4b4c-81b8-f18d27179305" width="25%" alt="Image">

## How to Test

- 내공연메인화면 이동 
- `티켓팅종료` 혹은 `관심공연` 메뉴탭 선택
- `티켓팅종료` 혹은 `관심공연`화면표출 확인 
- 데이터유무에 따른 `EmptyView`표출 확인

## Issues Resolved

- #131 

## Additional context

- `ShowDeleteCell`에서 사용하는 삭제버튼을 UIButton.Configuration에서 이미지 사이즈조절이 힘들어 `ShowDeleteButtonView`커스텀클래스를 이용하였습니다

## References

2024-08-19 15:36 UTC, ChoiysApple requested changes

2024-08-19 15:36 UTC, ChoiysApple commented on ShowPot/ShowPot/Domain/UseCase/InterestShow/InterestShowUseCase.swift
> +    var showList: BehaviorRelay<[ShowSummary]> { get }
`interestShowList` 로 바꾸는게 좋을 것 같습니다. 다른 부분도 비슷하게 바꿔주세요

1. 사용하는 입장에서 이게 무슨 showList인지 알기 어렵습니다. InterestShowUseCase라고 해서 무조건 관심 공연 리스트만 사용한다는 보장이 없습니다
2. 현재 usecase에서 다른 종류의 공연 리스트가 필요할 수 도 있습니다.  
3. usecase를 여러개 사용할 때도 문제가 될 수 있습니다.

2024-08-19 15:36 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Saved/EndShow/EndShowViewController.swift
> +final class EndShowViewController: ViewController {
End Show는 종료된 공연이 아니라, 공연을 종료시킨다는 동사입니다. 네이밍만 봐서는 특정 공연을 직접 종료시키는 네이밍에 더 가까워요

`ClosedShowListViewController`로 변경해주세요

2024-08-19 15:36 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Saved/InterestShow/CustomView/InterestShowEmptyView.swift
> +final class InterestShowEmptyView: UIView {
여기도 네이밍 `SavedShowView` 이런식으로 다 바꿔주세요

2024-08-20 11:28 UTC, dlrjswns commented on ShowPot/ShowPot/Domain/UseCase/InterestShow/InterestShowUseCase.swift
> +    var showList: BehaviorRelay<[ShowSummary]> { get }
@ChoiysApple 
아 이부분이 InterestShowUseCase안에 있는 공연리스트라 저번에 접두어관련해서 피드백들어서 저리 했던건데 수정하도록 하겠습니다 !!

2024-08-20 11:51 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Tab/Saved/InterestShow/CustomView/InterestShowEmptyView.swift
> +final class InterestShowEmptyView: UIView {
@ChoiysApple 
요부분이 `관심공연`, `티켓팅종료된 공연`데이터가 존재하지않을때 특정 화면에서만 사용하는 EmptyView인데 네이밍을 어떤식으로 바꿔야할까요 ??

2024-08-20 13:59 UTC, ChoiysApple approved these changes

2024-08-20 14:01 UTC, merged