[Fix] #146 icAlarm 이미지 사이즈 상이함
YAPP-Github/24th-App-Team-3-iOS pull request #148
Opened 2024-08-25 11:55 UTC by dlrjswns

## Describe

- 알림 이미지 디자인과 사이즈 동일하게 변경

## Works made

- `contentMode` 혹은 `사이즈`를 변경하면 `MenuCell`에 알림이미지를 제외한 다른 이미지까지 같이 작아져서 보이는게 결국 똑같아 피그마에서 `ic_alarm24`를 재 다운로드 하였습니다

## Changes Made

### As-Is

**기존 로직**
- `ic_alarm_navigation`이미지를 사용

**스크린샷**
<img src="https://github.com/user-attachments/assets/0d19df95-b6b0-4777-8131-0fb2dd29132c" width="25%" alt="Image">

### To-BE

**변경 로직**
- `ic_alarm24`이미지를 사용

**스크린샷**
<img src="https://github.com/user-attachments/assets/8b29c06e-9797-48c9-84ae-d1aab98c05d5" width="25%" alt="Image">

## How to Test

- `내 공연 메인화면`, `설정화면`에서 알림이미지 사이즈 확인

## Issues Resolved

- #146 

## Additional context

## References

2024-08-25 14:01 UTC, ChoiysApple requested changes
1. 하트 아이콘도 바꿔야합니다.
2. 이미지 아이콘 자체의 여백이 달라 발생하는 문제입니다. 배경색 넣어서 여백 확인해주세요

작업 끝나고 디자이너 검수 받아주세요

2024-08-25 17:39 UTC, dlrjswns commented
@ChoiysApple 
요거 원래 이미지자체에 여백이 있으면 다시 다운로드하는것말고는 방법이 없나요 ??

2024-08-26 05:48 UTC, ChoiysApple commented
> @ChoiysApple 
> 
> 요거 원래 이미지자체에 여백이 있으면 다시 다운로드하는것말고는 방법이 없나요 ??

자체 inset 주는 방식이 있는데 
디자인 가이드에서 inset을 지정해두고 디자인된게 아니라 방법 없어요

2024-08-26 10:23 UTC, dlrjswns commented
@ChoiysApple 
ic_heart_smaill, ic_heart_large 이미지를 추가했어요 
2가지를 추가한 이유는 `공연 상세`화면에서 관심버튼에서 토글할때에 `ic_heart_filled`와 사이즈가 통일돼야해서 
메뉴에서 사용하는 하트 이미지와 `small`과 `large`로 구분하게 했어요

2024-08-26 13:23 UTC, merged