[Feature] #199 설정화면 로그인 유무에 따른 메뉴 수정
YAPP-Github/24th-App-Team-3-iOS pull request #200
Opened 2024-09-03 12:06 UTC by dlrjswns

## Describe

- 설정화면에서 로그인 유무에 따라 설정 메뉴를 수정합니다

## Works made

- 로그인했다면, `계정메뉴`추가 혹은 보임
- 비로그인이라면, `계정메뉴`삭제 혹은 안보임

## Changes Made

### As-Is

**기존 로직**
<로그인된 상태>
- `설정화면`이동 시 `계정 메뉴`가 존재
- `계정 메뉴`클릭 시 `계정화면` 이동

<비로그인된 상태>
- `설정화면`이동 시 `계정 메뉴`가 존재
- `계정 메뉴`클릭 시 `로그인바텀시트` 표출

**동작 영상**
|로그인 상태|비로그인 상태|
|:-:|:-:|
https://github.com/user-attachments/assets/0f65c066-0644-4473-ab14-af65a5dfa779|https://github.com/user-attachments/assets/af7c3251-9dcd-4137-afe6-4ba9ecfcde25

### To-BE

**변경 로직**
<로그인된 상태>
- `설정화면`이동 시 `계정 메뉴`가 존재
- `계정 메뉴`클릭 시 `계정화면` 이동

<비로그인된 상태>
- `설정화면`이동 시 `계정 메뉴`가 존재 X

**동작 영상**
|로그인 상태|비로그인 상태|
|:-:|:-:|
https://github.com/user-attachments/assets/2809dbe3-247f-4e6c-b043-e5e198cae4bc|https://github.com/user-attachments/assets/385de160-fb2a-4d14-9bb7-2033a3c79295

## How to Test

- 로그인 유무에 따른 `설정화면`이동 
- 로그인 시 혹은 비로그인 시 `계정메뉴`가 존재하는지 확인 

## Issues Resolved

- #199 

## Additional context

- `개인정보방침`, `이용약관`관련 노션 URL이 수정되어 해당 PR에서 수정하였습니다

## References

2024-09-03 15:04 UTC, ChoiysApple requested changes

2024-09-03 15:04 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Settings/Setting/SettingViewController.swift
> +        viewModel.refreshSettingModel()
뷰컨에서 직접 viewModel의 값을 호출하는 것 보단
Input Output을 통해서만 정보전달이 이루어지는게 좋을 것 같아요

2024-09-03 15:04 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Settings/Setting/SettingViewController.swift
> +            title: Strings.settingNavigationTitle,
혹시 건준님이 개발한 화면들, title 문구 변수명이 모두 `000_navigation_title`로 되어있나요?

제가 개발한 쪽은 `000_title` 로 되어있어서, 나중에 리팩토링 할때 알아놔야 할거 같아서요

2024-09-03 15:04 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Settings/Setting/SettingViewController.swift
> +            }
버전정보 하나때문에 코드가 복잡해지는 감이 조금 있네요.
추후에 RxDataSource 또는 다른 방법으로 리팩토링 하는게 좋을 것 같아요

2024-09-03 15:04 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Settings/Setting/SettingViewController.swift
> +                    )
해당 Cell에서 사용하는 데이터가 `아이콘 이미지` `타이틀` `우측 텍스트` 3가지 인데 왜 2가지만 매개변수로 받나요?

우측 텍스트는 고정값으로 하드코딩되어있나요?

2024-09-03 15:04 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Settings/Setting/SettingViewModel.swift
> +    private let settingModelRelay = BehaviorRelay<[SettingType]>(value: [])
저희 일정때문에 세세하게 리뷰 못드렸는데 
input-output 패턴을 사용하는 만큼, 최대한 input-output 안에서만 해결하는 방식으로 가는게 좋을 것 같아요

input-output 객체 외부에서 값을 가지고 있으면, 데이터 하나를 여러개의 프로퍼티가 가지고 있어서 로직이 잘못될 위험 & 복잡성 증가 라는 단점이 있는것 같습니다

2024-09-03 15:04 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Settings/Setting/SettingViewModel.swift
> +    private let settingModelRelay = BehaviorRelay<[SettingType]>(value: [])
설정 화면에 표출될 항목들은
서버값이나 외부 변수에 의해 변경되는 값이 아니라, 고정적인 값이기 때문에 굳이 바인딩을 해야하나 싶습니다

2024-09-03 15:04 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Settings/Setting/SettingViewModel.swift
> +        let settingModel: Driver<[SettingType]>
다른 화면과 다르게 `Signal` `Driver`를 사용한 이유가 있나요?

2024-09-03 15:04 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Settings/Setting/SettingViewModel.swift
> +            var settingModel = self.settingModelRelay.value
바뀌지 않는 값이라서 `let`이 좋습니다

2024-09-03 15:04 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Settings/Setting/SettingViewModel.swift
> +            guard let versionIndex = settingModel.firstIndex(where: { $0 == .version }) else { return }
해당 구분 `contains` 사용하는게 좋을 것 같아요

2024-09-03 15:04 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Settings/Setting/SettingViewModel.swift
> +            self.versionAlertRelay.accept((versionIndex, alert))
`alert`이라는 네이밍은, 팝업과 같은 알림창 UI에 주로 사용됩니다 (현재 프로젝트 포함)
subText나 description같은 다른 네이밍으로 바꿔주세요

2024-09-03 15:04 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Settings/Setting/SettingViewModel.swift
건준님 `SettingsViewModel`이 있는데 이 네이밍은 너무 혼란스러워요
미래 이야기가 아니라 방금 이 파일 찾는데 `SettingsViewModel`로 이어져서 쓸떼없이 오래걸렸어요

네이밍 다 바꿔주세요

2024-09-03 15:04 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Settings/Setting/SettingViewModel.swift
> +    private let settingModelRelay = BehaviorRelay<[SettingType]>(value: [])
변수명에 `Relay`가 붙는게 비효율적인거 같아요

2024-09-03 15:16 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Tab/Settings/Setting/SettingViewController.swift
> +                    )
@ChoiysApple 
우측텍스트는 현재 버전이 최신버전인지 여부에 따라서 텍스트를 가져오고 있는데 이 부분을 담당하는 `SettingViewModel`의 `isUpdateAvailable`함수가 콜백으로 처리되고있어서 우측 텍스트는 `output.versionAlertMessage`로 버전여부가 방출되는것으로 처리하였습니다

최신버전여부를 가져오기까지 이미 고정값인 iconImage와 title이 안보이는건 안되기때문에 위처럼 2개 먼저 방출되게 하였습니다

2024-09-03 15:17 UTC, ChoiysApple commented
@dlrjswns 
건준님 그리고 이거 피쳐가 아니라 버그에요

2024-09-03 15:17 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Tab/Settings/Setting/SettingViewController.swift
> +            title: Strings.settingNavigationTitle,
@ChoiysApple 
아 네 맞습니다, 네비게이션 관련 타이틀은 전부 `000_navigation_title`이렇게 하였습니다

2024-09-03 15:19 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Tab/Settings/Setting/SettingViewModel.swift
@ChoiysApple 
아 이 부분 #125 이슈란에 작성해놓은 부분이긴한데 해당 PR에서 수정하도록 하겠습니다

2024-09-03 15:30 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Tab/Settings/Setting/SettingViewModel.swift
> +    private let settingModelRelay = BehaviorRelay<[SettingType]>(value: [])
@ChoiysApple 
요부분관련해서 `설정화면`은 이 PR에서 해결하고 나머지 제가 만든 `ViewModel`의 코드들도 따로 이슈만들어서 수정해서 올려드리겠습니다

2024-09-03 15:32 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Tab/Settings/Setting/SettingViewModel.swift
> +        let settingModel: Driver<[SettingType]>
@ChoiysApple 
다음 모델들은 UI에 바인딩되기때문에 `Signal`혹은 `Driver`가 어울린다고 생각했습니다.

2024-09-03 15:35 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Settings/Setting/SettingViewModel.swift
@dlrjswns 
네 아무리 Setting 네이밍이 맞아도 Settings가 있는데 저렇게 네이밍 짓는건 크게 잘못되었어요. Setting으로 네이밍 하실거였으면 Settings를 바꾸셨어야 합니다

이번 PR에 `Settings` 네이밍 `MyPage`로 바꿔주세요

2024-09-03 16:06 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Tab/Settings/Setting/SettingViewModel.swift
> +            guard let versionIndex = settingModel.firstIndex(where: { $0 == .version }) else { return }
@ChoiysApple 
음 이 코드가 `설정화면 메뉴리스트`중 `버전 메뉴`의 인덱스를 찾는 로직인데 `contains`를 사용한다면 어떤 코드를 생각하시는걸까요 ?

2024-09-04 09:58 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Settings/Setting/SettingViewController.swift
> +                    )
그러면 뷰 하나에 들어갈 데이터를 주입하는 부분이 여러개가 되어서 좋지 않고, `labelMenuCell` 재사용이 상당히 힘들어집니다.

아래 두가지 방법 중 한가지로 해결해주세요
1. 처음에 빈 문자열이나 default value를 주입하고 최신버전 여부 수신시 datasource 갱신
2. 버전체크 로직이 들어간 Cell을 개발해 사용

2024-09-04 10:01 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Settings/Setting/SettingViewModel.swift
> +            guard let versionIndex = settingModel.firstIndex(where: { $0 == .version }) else { return }
인덱스를 찾는 구문이 아니라 존재 여부를 찾는 로직으로 봤네요

여러 클로저가 한줄에 있거나 여러 종류의 동작이 구분 없이 나열되어 있어서 읽기 쉬운 코드는 아니라고 생각하는데, 일단 들여쓰기로 로직별로 나누어주는게 좋을 것 같습니다

2024-09-04 11:51 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Tab/Settings/Setting/SettingViewModel.swift
> +            guard let versionIndex = settingModel.firstIndex(where: { $0 == .version }) else { return }
@ChoiysApple 
요청해주신 부분 함수를 이용해서 다음 커밋에 반영해보았는데 확인 부탁드립니다.
[해당 커밋](https://github.com/YAPP-Github/24th-App-Team-3-iOS/pull/200/commits/dfb202d5245ac21091818751b3cd8a048f9fe601)

2024-09-04 11:53 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Tab/Settings/Setting/SettingViewController.swift
> +                    )
@ChoiysApple 
1번 방법을 이용해 `LabelMenuCell`에 하나의 configureUI함수를 이용하는 방법으로 수정하였습니다, 확인 부탁드립니다.
[해당 커밋](https://github.com/YAPP-Github/24th-App-Team-3-iOS/pull/200/commits/d21b45c304101b16116f5c0dd520dfda7b330fb2)

2024-09-04 14:50 UTC, ChoiysApple commented
@dlrjswns 
`Settings` 말고 다른것도 네이밍 바꾼거에요?
그리고 force push 하셨나요?

2024-09-09 11:31 UTC, ChoiysApple approved these changes

2024-09-10 06:48 UTC, merged