[Fix] #198 공연상세 관심등록/해제 미동작 문제 해결
YAPP-Github/24th-App-Team-3-iOS pull request #201
Opened 2024-09-09 11:53 UTC by dlrjswns

## Describe

- `공연상세`화면의 `관심 등록/해제` 미동작하는 문제를 해결 

## Works made

- `공연상세정보 조회` API의 누락되었던 `accessToken`관련 헤더를 추가
- `관심 등록/해제`시 비로그인 상태일때 `로그인 바텀시트`표출

## Changes Made

### As-Is

**기존 로직**
``` swift
func showDetail(showId: String) -> Observable<ShowDetailResponse> {
        let target = SPShowTargetType.showDetail(showId: showId)
        let accessToken = try? KeyChainManager.shared.read(account: .accessToken) 
        let id = UIDevice.current.identifierForVendor?.uuidString
        let header: HTTPHeaders = ["viewIdentifier": id ?? ""]
//... 생략
```
* `공연상세정보 조회` API에 대한 헤더값에 `accesssToken`이 누락된 채로 호출

**동작 영상**
|관심 등록/해제 시 갱신안되는 영상|
|:-:|
https://github.com/user-attachments/assets/aa6a1592-e29d-4c34-9fc0-a5585508e84c

### To-BE

**변경 로직**
``` swift
func showDetail(showId: String) -> Observable<ShowDetailResponse> {
        let target = SPShowTargetType.showDetail(showId: showId)
        let id = UIDevice.current.identifierForVendor?.uuidString
        
        var header: HTTPHeaders = ["viewIdentifier": id ?? ""]
        if let targetHeader = target.header {
            targetHeader.forEach { headerItem in
                header[headerItem.name] = headerItem.value
            }
        }
//... 생략
```
* `공연상세정보 조회` API의 헤더값에 `accesssToken`추가

**동작 영상**
|관심 등록/해제 시 갱신 확인 영상|관심 등록/해제 시 비로그인 상태일 때|
|:-:|:-:|
https://github.com/user-attachments/assets/7476d888-fe8d-4f93-82aa-ba65d294d4c5|https://github.com/user-attachments/assets/d0091680-8afc-4804-a358-1dc2790c639a

## How to Test

1. `공연 상세화면` 이동
2. `관심 등록/해제` 시도 
3. `비로그인 상태`일 때 `로그인유도 바텀시트`가 표출되는지 확인
4. `로그인 상태`일 때 화면 재진입하여도 올바르게 `관심 등록/해제`갱신되는지 확인

## Issues Resolved

- #198 

## Additional context

- #200 다음 이슈에서 언급했던 `Input/Output`패턴에 맞춰 `ViewModel`에 직접적으로 호출하는 코드를 수정하였습니다. -> [해당 커밋](https://github.com/YAPP-Github/24th-App-Team-3-iOS/commit/4181496cea5b4b623cf85901eea099767357da2e)

## References

2024-09-09 13:36 UTC, ChoiysApple requested changes

2024-09-09 13:36 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ShowDetail/ShowDetailViewController.swift
> +        viewHolder.seatInfoView.showSeatListView.delegate = self
delegate는 Style과 관련 없는 동작입니다

2024-09-09 13:36 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ShowDetail/ShowDetailViewController.swift
> +    private let refreshTrigger = PublishSubject<Void>()
커밋 이름과 무관한 수정내역입니다.
다음부턴 다른 커밋으로 분리해주세요

2024-09-09 13:36 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ShowDetail/ShowDetailViewController.swift
> +            viewWillAppear: refreshTrigger.asObservable(),
특정 함수가 호출되었을때 emitt 시키는 Observable이 있습니다
메이트러너 프로젝트에 사용 예시가 있으니 참고해서 변경해주세요.

2024-09-09 18:32 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ShowDetail/ShowDetailViewController.swift
> +        viewHolder.seatInfoView.showSeatListView.delegate = self
@ChoiysApple 
`setupStyles`는 UI관련 스타일이나 속성을 설정하는 곳입니다, 컬렉션뷰의 동작과 관련된 `delegate` 설정도 연관이 있다 생각하는데 실제로 코드에서 구현된 `delegate`함수는 컬렉션뷰셀의 사이즈를 정하는 역할이구요, `delegate`를 통해서 데이터 바인딩에 영향을 미치는것도 아니라서 `bind`보다 어울린다고 생각합니다

2024-09-10 15:16 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ShowDetail/ShowDetailViewController.swift
> +            viewWillAppear: refreshTrigger.asObservable(),
@ChoiysApple 
와 이런 호출방법이 있군요, 변경하였습니다 

[요청해주신 커밋 링크](https://github.com/YAPP-Github/24th-App-Team-3-iOS/pull/201/commits/20dcd9965677779b77e5fe64cb927eaf182921af)

2024-09-11 01:41 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ShowDetail/ShowDetailViewController.swift
> +            viewWillAppear: self.rx.methodInvoked(#selector(UIViewController.viewWillAppear)).map { _ in },
map 내부에 특별한 동작이 없는데, 이렇게 사용해야 할 이유가 있나요?

2024-09-11 05:33 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ShowDetail/ShowDetailViewController.swift
> +            viewWillAppear: self.rx.methodInvoked(#selector(UIViewController.viewWillAppear)).map { _ in },
@ChoiysApple 
`self.rx.methodInvoked(#selector(UIViewController.viewWillAppear))`의 리턴값이 `Observable<[Any]>`인데 저는 단순 `viewWillAppear`함수 호출 시점을 싶던거라서 `Observable<Void>`가 흐름상 맞다고 생각했어요 

대건님은 차라리 `ShowDetailViewModel.Input`의 `viewWillAppear`타입을 `Observable<[Any]>`로 두고 `map`을 지우는게 좋다는 의견이신가요 ??

2024-09-11 06:12 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ShowDetail/ShowDetailViewController.swift
> +            viewWillAppear: self.rx.methodInvoked(#selector(UIViewController.viewWillAppear)).map { _ in },
무슨말씀 하시는지는 이해했는데,

제 질문에 대한 답은 안하셨습니다

2024-09-11 06:27 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ShowDetail/ShowDetailViewController.swift
> +            viewWillAppear: self.rx.methodInvoked(#selector(UIViewController.viewWillAppear)).map { _ in },
@ChoiysApple 
map을 저렇게 사용한 이유는 방출하고있는 `[Any]`값 자체가 불필요하기때문에 이를 무시하기위해서 저런식으로 사용했습니다

2024-09-11 13:11 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ShowDetail/ShowDetailViewController.swift
> +            viewWillAppear: self.rx.methodInvoked(#selector(UIViewController.viewWillAppear)).map { _ in },
1. 해당 방식은 정상동작은 하지만 map이 동작이 없거나 잘못 동작하는것 처럼 보여 가독성이 떨어집니다. 이 방식을 고수하신다면 `.map { _ in Void() }` 처럼 어떠한 동작인지 명시적으로 볼 수 있는 방식이 좋을 것 같아요
2. 지금 Observable로 개발해두셨는데, Observable 스트림이 종료된다면 화면 갱신이 안되는 경우가 생길 수 있고 이는 영향도가 큰 이슈입니다. 언급한 상황을 염두하면서 수정해보세요

2024-09-12 07:54 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ShowDetail/ShowDetailViewController.swift
> +            viewWillAppear: self.rx.methodInvoked(#selector(UIViewController.viewWillAppear)).map { _ in },
@ChoiysApple 
1. 데이터바인딩 과정에서 스트림이 끊길 수 있어 기존 `Subject -> Relay`, `subscribe -> drive or signal`로 변경
2. `공연상세화면 조회`, `관심 등록/해제` API 호출 시 `onError`방출했을때 `catch`연산자를 이용해 스트림이 끊지않게 하였습니다 (`CustomError`를 `apiService`에서 방출하게해서 스트림 끊기지않음을 확인하였습니다)
3. `관심 버튼`에 `throttle`을 추가해 너무 과다한 API호출을 방지하였습니다

한번 확인해보시고 리뷰부탁드립니다

2024-09-13 02:21 UTC, ChoiysApple commented
@dlrjswns 
건준님 작업 다 하신건가요?
리뷰 요청이 안되어있어서요

2024-09-13 06:21 UTC, dlrjswns commented
@ChoiysApple 
아 작업이 전부 완료되긴했는데 맨 상단에 `delegate = self`부분 답변이 없으셔서 기다리고있었어요 !
기존 대건님 작업물처럼 `viewDidLoad`에 삽입할까요 ?

2024-09-13 06:35 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ShowDetail/ShowDetailViewController.swift
> +        viewHolder.seatInfoView.showSeatListView.delegate = self
`BaseViewController`내부에 이렇게 구현되어있습니다. 이건 제가 개발한게 아니라 건준님이 쓰던 코드를 가져온거에요
```swift
/// 현재 ViewController의 view 관련 설정 코드
    ///
    /// ***i.e.*** self.title = "title"
    func setupStyles() {
        self.view.backgroundColor = .gray700
    }
```

`UIViewController`의 `view`에 관한 설정들을 모아놓은 메서드입니다
근데 저 부분은 `viewHolder`에 관한 설정입니다. 애초에 `ViewHolder`로 UI 코드를 분리했는데, 저 코드가 `setUpStyle()`에 들어가면 기껏 분리해놓은 뷰 로직들이 다시 합쳐지는 모양새가 됩니다

2024-09-13 07:11 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ShowDetail/ShowDetailViewController.swift
> +        viewHolder.seatInfoView.showSeatListView.delegate = self
@ChoiysApple 
넵 `viewDidLoad`에 옮겨놓도록 하겠습니다 !

2024-09-18 12:31 UTC, ChoiysApple commented on ShowPot/ShowPot/Domain/UseCase/ShowDetail/DefaultShowDetailUseCase.swift
> +            .catch { _ in return .empty() }
지금 하신것처럼 `catch`사용하거나 `Relay` 사용해서 이런 처리를 해둘건데,

나중에 PD쪽에서 정해주면 팝업 띄우거나 다른 공통 동작을 넣어주게 될 것 같아요

2024-09-18 12:34 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ShowDetail/ShowDetailViewController.swift
> +            .asDriver(onErrorJustReturn: [])
데이터 관련된 것들은 에러 상황에서 기본값을 넣어 주는 것만으로는 부족할 수 있어요. 
추후에 ticketBrandList에 emit 하는 부분에서 에러 처리 로직이 필요할 것 같네요

2024-09-18 12:35 UTC, ChoiysApple approved these changes

2024-09-18 15:50 UTC, HyeonSeok7 commented on ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ShowDetail/ShowDetailViewModel.swift
> +            .throttle(.seconds(1), latest: false, scheduler: ConcurrentDispatchQueueScheduler.init(qos: .default))
@dlrjswns 
Android와 기준이 다를 수 있지만, 
보통 저는 유저의 사용성을 위해서 중복 클릭 방지를 할 때의 시간은
300ms or 500ms로 줍니다. (버벅이거나 안눌리는듯한 느낌을 받게한다고 느껴서요.)
혹시 1초라는 시간을 주신 기준이 있을까요?

2024-09-18 15:50 UTC, HyeonSeok7 commented on ShowPot/ShowPot/Domain/UseCase/ShowDetail/DefaultShowDetailUseCase.swift
> +            .catch { _ in return .empty() }
@dlrjswns 
catch문에 걸렸을때 emptyList 를 반환해주는건 이해했습니다.
그런데 정말 실제로 데이터가 없을 경우에 emptyList와
문제가 생겨서 반환된 emptyList를 구분하기 어려울 것 같아요.

결국 그러면 어디가 문제인지 전부 다시 봐야하는데,
carch와 같은 error가 발생해서 발생되는 코드에는 Log.e 와 같은걸 달아서
역추적하기 편하게 하면 어떨까요?

당장 달지 않고! 동료(?)분과 공통 컨벤션 정해서 진행하면 좋을 것 같아요 .

2024-09-18 15:50 UTC, HyeonSeok7 commented on ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ShowDetail/ShowDetailViewController.swift
> +                let (isUpdatedBefore, isAlreadyOpen) = result
@dlrjswns 
isUpdatedBefore는 어떤 의미인가요?

2024-09-18 15:50 UTC, HyeonSeok7 commented on ShowPot/ShowPot/Domain/UseCase/ShowDetail/DefaultShowDetailUseCase.swift
> +                owner.updateInterestResult.onNext(response.hasInterest)
@dlrjswns 
함수의 이름은 Show가 포함되었는데
왜 Result에는 Show라는 명칭이 빠진거에요?

통일해서 가면 더 좋을 것 같아요.

2024-09-18 15:53 UTC, ChoiysApple requested changes
현석님이 달아준 리뷰 확인해주세요
수정 필요할 듯 합니다

2024-09-18 15:55 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ShowDetail/ShowDetailViewModel.swift
> +            .throttle(.seconds(1), latest: false, scheduler: ConcurrentDispatchQueueScheduler.init(qos: .default))
이부분 확인 못했는데, 1초는 확실히 너무 깁니다. 1초 정도의 시간은 대부분의 유저 입장에서 앱이 버벅인다고 느낄 수 있어요

2024-09-18 16:48 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ShowDetail/ShowDetailViewModel.swift
> +            .throttle(.seconds(1), latest: false, scheduler: ConcurrentDispatchQueueScheduler.init(qos: .default))
@HyeonSeok7 
아 1초를 준 이유는 단순 너무 많은 클릭방지하기위해 넣었어요, 0.5초정도로 수정하겠습니다 !

2024-09-18 16:49 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ShowDetail/ShowDetailViewController.swift
> +                let (isUpdatedBefore, isAlreadyOpen) = result
@HyeonSeok7 
이전에 알림설정을 통해 업데이트한적이 있는지에 대한 의미입니다 !

2024-09-18 17:25 UTC, dlrjswns commented on ShowPot/ShowPot/Domain/UseCase/ShowDetail/DefaultShowDetailUseCase.swift
> +            .catch { _ in return .empty() }
@HyeonSeok7 
일단 .empty()가 방출되게되면은 이후 스트림은 동작하지않고 종료되는 로직입니다
요청해주신 로그는 API를 호출하는 request함수내부에서 찍는 방향이 좋을꺼같다는 의견입니다 !!(모든 catch문마다 로그를 찍는건 비효율적이라 생각해요)

위에 대건님이 말씀해주신것처럼 PM님과 에러처리에 대한 협의가 정해지면 수정하면 좋을꺼같아요 
너무 좋은 의견 감사드립니다 :)

2024-09-18 17:27 UTC, dlrjswns commented on ShowPot/ShowPot/Domain/UseCase/ShowDetail/DefaultShowDetailUseCase.swift
> +                owner.updateInterestResult.onNext(response.hasInterest)
@HyeonSeok7 
함수이름을 `updateInterest`로 변경하도록 하겠습니다 !

2024-09-18 23:46 UTC, HyeonSeok7 commented on ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ShowDetail/ShowDetailViewController.swift
> +            viewWillAppear: self.rx.methodInvoked(#selector(UIViewController.viewWillAppear)).map { _ in },
@dlrjswns 
궁금한게 있습니다.
onError를 방출했을떄 catch 연산자를 이용해 스트림을 끊기지 않게 하는건가요? 혹은
onError를 방출했을때, 스트림이 끊김과는 상관없이 catch문에서 그 말대로 catch하기 위함인가요?

2024-09-19 07:19 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ShowDetail/ShowDetailViewController.swift
> +            viewWillAppear: self.rx.methodInvoked(#selector(UIViewController.viewWillAppear)).map { _ in },
@HyeonSeok7 
`catch` 연산자는 `onError`로 인해 스트림이 끊기지 않게 하기 위해 사용할 수 있습니다. 또한 말씀하신대로 오류를 처리하는 역할도 할 수 있습니다

2024-09-19 07:39 UTC, HyeonSeok7 commented on ShowPot/ShowPot/Domain/UseCase/ShowDetail/DefaultShowDetailUseCase.swift
> +            .catch { _ in return .empty() }
@dlrjswns 
말씀하신 비효율적인 측면에서는, API를 호출하는 모든 request 함수에서 찍는게 안좋지 않나요. 아니면 다른 의미였는지 궁금해요.
catch는 onError가 발생했을 때에만 찍히는 로그이니, 위에 말씀해주신 관점으로 봤을떄 봤을때는 상대적으로 효율적이지 않나싶어요.
(프로젝트가 크면 커지면 커질 수록 역추적하기가 많이 힘들어져서..

2024-09-19 07:44 UTC, HyeonSeok7 commented on ShowPot/ShowPot/Domain/UseCase/ShowDetail/DefaultShowDetailUseCase.swift
> +                owner.updateInterestResult.onNext(response.hasInterest)
@dlrjswns
어 아니요 저는 반대로 updateShowInterest가 더 좋다고 생각해서 말씀드린거에요
어떤 관심을 업데이트한다는건지 남이 보면 모를 것 같아요.
공연에 대한 관심을 업데이트한다는 이름이 더 직관적이지 않을까 싶습니다.

2024-09-19 07:52 UTC, dlrjswns commented on ShowPot/ShowPot/Domain/UseCase/ShowDetail/DefaultShowDetailUseCase.swift
> +            .catch { _ in return .empty() }
@HyeonSeok7 
아 현재 구조에서는 API마다 함수를 만들어서 `responseDecodable`를 호출하는 형식인데 이건 데모데이맞춰서 임의로 짜진거라 아마 개선이 된다면 하나의 `request`함수를 이용하는 구조라 짜지면 해당 함수내부에서 에러 방출했을때에 로그를 찍는걸 말씀드렸어요 !

2024-09-19 08:11 UTC, dlrjswns commented on ShowPot/ShowPot/Domain/UseCase/ShowDetail/DefaultShowDetailUseCase.swift
> +                owner.updateInterestResult.onNext(response.hasInterest)
@HyeonSeok7 

요청해주신 부분이 아래와 같을까요 ?
[반영한 커밋 링크](https://github.com/YAPP-Github/24th-App-Team-3-iOS/pull/201/commits/5fe27273165fc07400d00488914ebb68346df3ce)

2024-09-19 08:47 UTC, HyeonSeok7 commented on ShowPot/ShowPot/Domain/UseCase/ShowDetail/DefaultShowDetailUseCase.swift
> +                owner.updateInterestResult.onNext(response.hasInterest)
@dlrjswns 
맞아요! 항상 변수명은 쉽고 명확하게 짓고 싶은데 쉽지 않아요..너무 어렵네요.. 
그렇다고 모든 의미를 표현하려고 너무 길게 짓는 것도 좋지 않은 방법이니깐요

변수/함수명을 지을떄
1. 쉽게 (읽히게)
2. 명확하게
3. 다른 협업 혹은 개발자가 봤을때도 쉽고 명확한가 입장바꿔서 생각해보기

동료랑 항상 공유하고 머리 맞대고 고민해보는 것도 좋습니다.

여러번 수정하느라 고생하셨어요 :)

2024-09-20 14:27 UTC, ChoiysApple requested changes

2024-09-20 14:27 UTC, ChoiysApple commented on ShowPot/ShowPot/Domain/UseCase/ShowDetail/DefaultShowDetailUseCase.swift
> +    var updateShowInterestResult = PublishSubject<Bool>()
변수명에는 동사를 쓰지 않고 명사를 사용하는게 좋습니다. 동사는 동작을 지칭하기 때문에 실제 동작이 있는 함수 등에 사용되는게 좋아요.

이 변수명을 해석하면 "공연 관심 결과 업데이트"인데, 변수명으로 어떤 변수인지 감조차 오지 않네요

2024-09-20 14:27 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ShowDetail/ShowDetailViewModel.swift
> +            .throttle(.milliseconds(500), latest: false, scheduler: ConcurrentDispatchQueueScheduler.init(qos: .default))
500ms라는 수치는 어떠한 기준으로 잡으셨나요?
실제 테스트를 해보고 정한 수치인가요?

2024-09-21 08:18 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ShowDetail/ShowDetailViewModel.swift
> +            .throttle(.milliseconds(500), latest: false, scheduler: ConcurrentDispatchQueueScheduler.init(qos: .default))
@ChoiysApple 
일단 현석님 PR확인하고 로그를 찍어봤더니 기존 적용한 `1초`라는 시간이 생각보다 반응이 느려서 추천해주신 `500ms`로 잡고 버튼을 연속으로 눌렀을 때도 딜레이가 크게 느껴지지 않아 자연스러운 느낌을 받아 정하게 되었습니다

혹시 대건님이 생각하시는 적당한 수치가 있으실까요 ?

2024-09-21 08:19 UTC, dlrjswns commented on ShowPot/ShowPot/Domain/UseCase/ShowDetail/DefaultShowDetailUseCase.swift
> +    var updateShowInterestResult = PublishSubject<Bool>()
@ChoiysApple 
대건님이 언급해주신 저 부분말고도 `Clean Code`참고하여 한번 수정하고 요청해보겠습니다

2024-09-21 10:07 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ShowDetail/ShowDetailViewModel.swift
> +            .throttle(.milliseconds(500), latest: false, scheduler: ConcurrentDispatchQueueScheduler.init(qos: .default))
300ms라는 수치도 제시됬는데, 이건 테스트 안해보셨나요?

2024-09-21 10:36 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Tab/Saved/ShowDetail/ShowDetailViewModel.swift
> +            .throttle(.milliseconds(500), latest: false, scheduler: ConcurrentDispatchQueueScheduler.init(qos: .default))
@ChoiysApple 
`300ms`와 `500ms` 둘 다 해보았습니다, 헌데 `500ms`로 했을때 제가 의도했던 `중복요청방지`에 도움이 된다 판단했어요, `latest`를 false로 명시적으로 표현한 이유도 같은 이유이구요. 

`300ms`는 빠르게 반응한다는 장점이 있었지만 원치않은 중복요청이 있을 수 있다 판단했어요.

정답이 있다기보단 추천해준 범위 중 좀 더 안정적인 부분에 초점을 맞췄던거같습니다

2024-09-21 10:52 UTC, dlrjswns commented
@ChoiysApple 
1. `updatedShowInterestResult`라는 명사구로 변경
2. 기존 `~list`라는 네이밍을 사용해왔는데 Relay가 가지고있는 value, 즉 `list`라는 컨테이너에 초점을 맞춘 네이밍이였습니다, 이를 `데이터 자체`의미로 해석하기위해서 `~model`로 변경해보았습니다.

2024-09-21 11:03 UTC, ChoiysApple commented
> @ChoiysApple
> 
> 1. `updatedShowInterestResult`라는 명사구로 변경
> 2. 기존 `~list`라는 네이밍을 사용해왔는데 Relay가 가지고있는 value, 즉 `list`라는 컨테이너에 초점을 맞춘 네이밍이였습니다, 이를 `데이터 자체`의미로 해석하기위해서 `~model`로 변경해보았습니다.

변수명이 이해하기 쉬운지 정확하게 알아보려고 의도적으로 코드를 분석하지 않고, 변수명만 보다보니 해당 변수가 뭔지 이해 못하고 있어서 피드백이 조금 어긋난거 같아요.

저 변수가 `공연 관심 등록 API`결과를 받아오는 스트림이죠?
api 요청의 결과인데 저게 `어떤 동작의 결과`인지 알기 힘든 네이밍이기 때문에 이런 미스매치가 발생했다고 생각해요.

이 부분에 맞춰서 변수명을 다시 고쳐보면 좋을 것 같은데, @HyeonSeok7  조언 부탁해용

2024-09-21 11:25 UTC, dlrjswns commented
> > @ChoiysApple
> > 
> > 1. `updatedShowInterestResult`라는 명사구로 변경
> > 2. 기존 `~list`라는 네이밍을 사용해왔는데 Relay가 가지고있는 value, 즉 `list`라는 컨테이너에 초점을 맞춘 네이밍이였습니다, 이를 `데이터 자체`의미로 해석하기위해서 `~model`로 변경해보았습니다.
> 
> 변수명이 이해하기 쉬운지 정확하게 알아보려고 의도적으로 코드를 분석하지 않고, 변수명만 보다보니 해당 변수가 뭔지 이해 못하고 있어서 피드백이 조금 어긋난거 같아요.
> 
> 저 변수가 `공연 관심 등록 API`결과를 받아오는 스트림이죠? api 요청의 결과인데 저게 `어떤 동작의 결과`인지 알기 힘든 네이밍이기 때문에 이런 미스매치가 발생했다고 생각해요.
> 
> 이 부분에 맞춰서 변수명을 다시 고쳐보면 좋을 것 같은데, @HyeonSeok7 조언 부탁해용

맞습니다 `공연 관심 등록/해제 API` 응답값을 받아오는 스트림입니다

2024-09-23 13:47 UTC, merged