[Fix] #203 공연 티켓팅 알림 셀에 대한 stroke color문제 해결
YAPP-Github/24th-App-Team-3-iOS pull request #204
Opened 2024-09-11 09:26 UTC by dlrjswns

## Describe

- `티켓팅알림설정/변경 바텀시트`에서 해당 시간이 사용불가상태일때 `stroke color` 적용

## Works made

- `티켓팅 알림`에 대한 시간이 사용불가상태일때 `strokeColor`를 `gray500`적용

## Changes Made

### As-Is

**기존 로직**
``` swift
if !isEnabled {
    checkImageView.removeFromSuperview()
    checkImageView.snp.removeConstraints()
    contentView.addSubview(disEnabledAlertLabel)
    disEnabledAlertLabel.snp.makeConstraints {
        $0.trailing.equalToSuperview().inset(18)
        $0.centerY.equalToSuperview()
        $0.leading.equalTo(timeInfoLabel)
    }
    timeInfoLabel.textColor = .gray400
    return
}
```
- `사용불가상태(isEnabled == false)`일때 아무런 `strokeColor`가 적용되지않음

**스크린샷**
<img src="https://github.com/user-attachments/assets/b40191dd-3400-450f-a01f-c481f288495a" width="25%" alt="Image">

### To-BE

**변경 로직**
``` swift
if !isEnabled {
    checkImageView.removeFromSuperview()
    checkImageView.snp.removeConstraints()
    contentView.addSubview(disEnabledAlertLabel)
    disEnabledAlertLabel.snp.makeConstraints {
        $0.trailing.equalToSuperview().inset(18)
        $0.centerY.equalToSuperview()
        $0.leading.equalTo(timeInfoLabel)
    }
    timeInfoLabel.textColor = .gray400
    contentView.layer.borderColor = UIColor.gray500.cgColor <- `사용불가상태`일때 `strokeColor`를 적용
    return
}
```

**스크린샷**
<img src="https://github.com/user-attachments/assets/0e121f2d-4215-4a10-bf7b-c52b03a0e4df" width="25%" alt="Image">

## How to Test

1. `공연상세`화면 이동 
2. `알림설정/변경하기`버튼 클릭
3. `티켓팅 알림 사용불가`상태일때 strokeColor가 올바르게 `gray500`이 적용됐는지 확인

## Issues Resolved

- #203 

## Additional context

- 다음 이슈를 수정하던 중 추가적으로 발견한 이슈가 존재합니다

|티켓팅 알림 선택/미선택 시 하단 잔상이 남는 이슈 영상|
|:-:|
https://github.com/user-attachments/assets/bbcc2b6a-83d7-4470-a959-90dc6a099966
- 위 영상에서 보이는 잔상문제가 `iPhone 13 mini` 시뮬레이터에서 나타나는 이슈로 보입니다(시뮬레이터에서만 나타나는 이슈일수도)

@ChoiysApple 
- 해결 아이디어가 떠오르지않아 Draft전환 후 요청드립니다 🙋🏻‍♂️

## References

[해당 이슈리스트 노션 링크](https://www.notion.so/yapp-workspace/207f15977e20479b96d051de03e75118?p=b76aa71252cd4d3aa6fa20e2972ee7dc&pm=s)

2024-09-11 13:16 UTC, ChoiysApple commented
@dlrjswns 
막혀서 질문하실때는 원인분석이 어디까지 되었는지, 어느 부분에서 막히는지 등 최대한 시도해보고 이를 정리해서 알려주셔야합니다
당연히 여러 상황이나 기기에서 테스트는 기본적으로 하셔야하구요

2024-09-11 23:20 UTC, dlrjswns commented
@ChoiysApple 
해결한 스크린샷 부분에서 하단에 약간의 겹침이 보이는데 실제 시뮬레이터와 실기기상으로는 보이지않는거같습니다, `command + shift + 4`로 캡처하면 보이는 현상같습니다.

시뮬레이터 `Save Screen`을 이용해 캡처하니 올바르게 보입니다.
<img src="https://github.com/user-attachments/assets/1ae2f171-faa1-4080-8c86-35c7deb4e6db" width="25%" alt="Image">

## 문제 설명
현재 `티켓팅알림관련 컬렉션뷰 셀`, `하단 알림설정/변경 버튼`에서, 여러 기기에서 정상 동작을 확인했으나 `iPhone 13 mini`, `iPhone 12 mini` 시뮬레이터에서만 하단에 배경색이 남아있는 문제가 발생했습니다.

## 테스트한 기기
### 정상 작동 기기 (시뮬레이터):
* iPhone 15
* iPhone 15 Pro Max
* iPhone XS
* iPhone SE 3세대
* iPhone 12
* iPhone 13
### 문제 발생 기기 (시뮬레이터):
* iPhone 13 mini
* iPhone 12 mini
### 실기기 테스트:
* iPhone 8 (문제 발생 여부 확인 불가)

## 시도한 해결 방법

### 1. UIButton.Configuration의 타입 변경:
* 처음에는 `filled()`로 설정한 상태였으며, 다른 설정 값이 부가적으로 들어갔다고 판단하여 `plain()`으로 변경해보았습니다.
* 그러나 여전히 `iPhone 13 mini`, `iPhone 12 mini`에서만 하단에 배경색이 남아있는 현상이 나타났습니다.
### 2. UIButton.Configuration의 stroke 속성 초기화:
* 문제의 원인이 버튼의 테두리 설정(strokeColor 및 strokeWidth)일 수 있다고 판단하여, 이 속성을 명시적으로 초기화하였습니다.
``` swift
configuration.strokeColor = nil
configuration.strokeWidth = 0
```
그러나 문제는 여전히 해결되지 않았습니다.

### 3. 다양한 기기 테스트
* `Notch` 혹은 `홈 버튼`이 있는 기기에서만 나타나는 이슈인지 해서 다른 시뮬레이터 기기와 실기기로 테스트해보았습니다.

* 여러 시뮬레이터 기기에서 테스트한 결과, 문제는 `iPhone 13 mini`, `iPhone 12 mini`에서만 발생하고 있습니다.
* 실기기로는 `iPhone 8`에서만 테스트해보았고, 이 기기에서는 문제를 확인할 수 없었습니다.

##  도움 요청
* 이슈가 mini관련 기기에서만 발생하는 것 같아서 혹시 다른 설정이나 추가적인 테스트가 필요할지에 대해 대건님 피드백을 받고싶습니다.

2024-09-12 04:42 UTC, dlrjswns commented
@ChoiysApple 
해결한 스크린샷 부분에서 하단에 약간의 겹침이 보이는데 저 스크린샷이 `선택불가`일때 셀에 보이는 `strokeColor`를 해결한 부분이라 여전히 하단 잔상이 보이는거 같습니다

## 문제 설명
현재 `티켓팅알림관련 컬렉션뷰 셀`, `하단 알림설정/변경 버튼`에서, 여러 기기에서 정상 동작을 확인했으나 `iPhone 13 mini`, `iPhone 12 mini` 시뮬레이터에서만 하단에 배경색이 남아있는 문제가 발생했습니다.

## 테스트한 기기
### 정상 작동 기기 (시뮬레이터):
* iPhone 15
* iPhone 15 Pro Max
* iPhone XS
* iPhone SE 3세대
* iPhone 12
* iPhone 13
### 문제 발생 기기 (시뮬레이터):
* iPhone 13 mini
* iPhone 12 mini
### 실기기 테스트:
* iPhone 8 (문제 발생 여부 확인 불가)

## 시도한 해결 방법

### 1. UIButton.Configuration의 타입 변경:
* 처음에는 `filled()`로 설정한 상태였으며, 다른 설정 값이 부가적으로 들어갔다고 판단하여 `plain()`으로 변경해보았습니다.
* 그러나 여전히 `iPhone 13 mini`, `iPhone 12 mini`에서만 하단에 배경색이 남아있는 현상이 나타났습니다.
### 2. UIButton.Configuration의 stroke 속성 초기화:
* 문제의 원인이 버튼의 테두리 설정(strokeColor 및 strokeWidth)일 수 있다고 판단하여, 이 속성을 명시적으로 초기화하였습니다.
``` swift
configuration.strokeColor = nil
configuration.strokeWidth = 0
```
그러나 문제는 여전히 해결되지 않았습니다.

### 3. 다양한 기기 테스트
* `Notch` 혹은 `홈 버튼`이 있는 기기에서만 나타나는 이슈인지 해서 다른 시뮬레이터 기기와 실기기로 테스트해보았습니다.

* 여러 시뮬레이터 기기에서 테스트한 결과, 문제는 `iPhone 13 mini`, `iPhone 12 mini`에서만 발생하고 있습니다.
* 실기기로는 `iPhone 8`에서만 테스트해보았고, 이 기기에서는 문제를 확인할 수 없었습니다.

##  도움 요청
* 이슈가 mini관련 기기에서만 발생하는 것 같아서 혹시 다른 설정이나 추가적인 테스트가 필요할지에 대해 대건님 피드백을 받고싶습니다.

2024-09-12 05:02 UTC, ChoiysApple commented
실기기로 확인 안된다는게 무슨말이에요?
실기기 빌드가 안되는 상황인가요?

mini는 제가 퇴근하고 실기기 빌드 돌려볼게요

2024-09-12 09:50 UTC, dlrjswns commented
> 실기기로 확인 안된다는게 무슨말이에요? 실기기 빌드가 안되는 상황인가요?
> 
> mini는 제가 퇴근하고 실기기 빌드 돌려볼게요

아 `실기기(iPhone 8)`에서 확인해보니 해당 이슈가 발견하지않는다는 말이였습니다.
이해하기쉽도록 수정하도록 하겠습니다, 넵 감사드립니다 😭😭

2024-09-12 12:07 UTC, ChoiysApple commented
> > 실기기로 확인 안된다는게 무슨말이에요? 실기기 빌드가 안되는 상황인가요?
> > mini는 제가 퇴근하고 실기기 빌드 돌려볼게요
> 
> 아 `실기기(iPhone 8)`에서 확인해보니 해당 이슈가 발견하지않는다는 말이였습니다. 이해하기쉽도록 수정하도록 하겠습니다, 넵 감사드립니다 😭😭



> > 실기기로 확인 안된다는게 무슨말이에요? 실기기 빌드가 안되는 상황인가요?
> > mini는 제가 퇴근하고 실기기 빌드 돌려볼게요
> 
> 아 `실기기(iPhone 8)`에서 확인해보니 해당 이슈가 발견하지않는다는 말이였습니다. 이해하기쉽도록 수정하도록 하겠습니다, 넵 감사드립니다 😭😭

12 mini에서 확인했는데 어색하게 동작하거나 상기한 이슈는 발생하지 않네요
시뮬레이터 버그로 판단하고, 추후에 여러 기기에서 테스트할때 재발하면 그때 다시 처리하시죠

2024-09-12 13:44 UTC, dlrjswns commented
> > > 실기기로 확인 안된다는게 무슨말이에요? 실기기 빌드가 안되는 상황인가요?
> > > mini는 제가 퇴근하고 실기기 빌드 돌려볼게요
> > 
> > 
> > 아 `실기기(iPhone 8)`에서 확인해보니 해당 이슈가 발견하지않는다는 말이였습니다. 이해하기쉽도록 수정하도록 하겠습니다, 넵 감사드립니다 😭😭
> 
> 12 mini에서 확인했는데 어색하게 동작하거나 상기한 이슈는 발생하지 않네요 시뮬레이터 버그로 판단하고, 추후에 여러 기기에서 테스트할때 재발하면 그때 다시 처리하시죠



> > > 실기기로 확인 안된다는게 무슨말이에요? 실기기 빌드가 안되는 상황인가요?
> > > mini는 제가 퇴근하고 실기기 빌드 돌려볼게요
> > 
> > 
> > 아 `실기기(iPhone 8)`에서 확인해보니 해당 이슈가 발견하지않는다는 말이였습니다. 이해하기쉽도록 수정하도록 하겠습니다, 넵 감사드립니다 😭😭
> 
> 12 mini에서 확인했는데 어색하게 동작하거나 상기한 이슈는 발생하지 않네요 시뮬레이터 버그로 판단하고, 추후에 여러 기기에서 테스트할때 재발하면 그때 다시 처리하시죠

넵 확인했습니다, Draft풀도록 하겠습니다
마지막으로 확인하시고 승인해주시면 rebase이후 merge하도록 하겠습니다

2024-09-18 12:43 UTC, ChoiysApple requested changes
이 이슈 단순 UI 설정이 아니라 재사용 이슈로 보이네요
재사용 이슈이면 이 작업만으로는 사이드 발생활 확률이 높아보이는데 확인 한번 더 해주세요

2024-09-19 10:28 UTC, dlrjswns commented
@ChoiysApple 
1. 기존 `updateIfNeeded`함수가 `isEnabled`, `isChecked`의 didSet을 통해 호출되고있어서 `configureUI`함수 한번 동작할때마다 2번씩 호출되는 부분을 1번만 호출되게 수정했습니다

2. `prepareForReuse`함수를 작성하고 `updateIfNeeded`가 비대해지다보니 다소 가독성이 떨어진다생각해서 `updateUI`, `updateLayout`으로 함수를 이용해 분리해보았습니다 

한번 확인해보시고 코멘트부탁드립니다 😀😀

2024-09-20 14:30 UTC, ChoiysApple requested changes
네이밍 하나만 바꿔주세요

2024-09-20 14:30 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Saved/MyShowAlarm/CustomView/TicketingAlarmCell.swift
> +    private func updateIfNeeded() {
`layoutIfNeeded()`라는 기존 UIKit 함수가 있어서 이런 식으로 네이밍 하신거 같네요

하지만 실제 `layoutIfNeeded` 또는 비슷한 네이밍의 퍼스트 파티 함수와 혼동할 여지가 많고, 네이밍 자체가 이해하기 쉽지는 않아서 바꾸는게 좋을 것 같네요

2024-09-23 13:49 UTC, merged