[Feature] #20 Logger를 활용한 Common 로그기능 개발
YAPP-Github/24th-App-Team-3-iOS pull request #23
Opened 2024-06-12 16:18 UTC by dlrjswns

## Describe
`Logger`인스턴스를 활용하여 debug, info, notice, error 레벨에 해당하는 API를 쉽게 사용할 수 있도록 추상화 작업을 진행

## Works made

* ShowPot 프로젝트 특성상 iOS 14 이상이므로 Logger의 debug, info, notice, error레벨을 활용해 로그 함수를 개발 
* 로그를 호출한 함수이름, 호출한 줄, 호출한 클래스를 `Console` 혹은 `Xcode Console`에서 확인하여 명확한 로그 가능
* String inteporation의 align을 이용해 `Console`에서 보기 깔끔하게 구현

## Changes Made

### As-Is
**기존 로직**
* 로그를 위해 print문을 이용하게되어 보기 불편

### To-BE
**변경 로직**
* Logger의 category를 활용해 원하는 로그를 보기 편리
* 앱에 관련된 로그를 디스크에 저장하여 런타임에 발생하는 로그를 통해 앱에 관련된 이슈해결에 도움이 될 것으로 판단
* 로그를 호출한 클래스, 함수 등등에 대한 정보를 간편하게 확인가능

**스크린샷**
#### Console 앱 로그(하위시스템을 이용해 필터링하여 로그 보기)
<img width="1070" alt="스크린샷 2024-06-13 오전 12 59 16" src="https://github.com/YAPP-Github/24th-App-Team-3-iOS/assets/39263235/5a52e413-f801-477e-ab44-952dad5348c6">

#### Xcode Console 로그
<img width="494" alt="스크린샷 2024-06-13 오전 12 45 51" src="https://github.com/YAPP-Github/24th-App-Team-3-iOS/assets/39263235/de888a5f-b979-400a-bf95-29019568e479">

## How to Test
**코드 사용법**
``` swift
LogHelper.debug("LogHelper Debug API 호출", privacy: .public)
LogHelper.notice("LogHelper notice API 호출", privacy: .public)
LogHelper.error("LogHelper error API 호출", privacy: .public)
LogHelper.info("LogHelper info API 호출", privacy: .public)
```
<img width="368" alt="스크린샷 2024-06-13 오전 1 11 00" src="https://github.com/YAPP-Github/24th-App-Team-3-iOS/assets/39263235/64a8a526-c903-41a1-bbdb-24b84145b64f">

* 반드시 콘솔앱의 동작 메뉴에서 `정보 메세지 포함`, `디버그 메세지 포함` 설정을 킨 이후에 스트리밍 시작하셔야 올바르게 로그를 받으실 수 있습니다.

## Issues Resolved
- #20 

## Additional context
* Logger의 debug 레벨을 사용하는 경우 `Console` 앱에서는 찍히지않고 `Xcode Console`에서만 확인가능
* `Console` 앱에서 카테고리 혹은 하위시스템을 이용해 원하는 로그 검색가능
* Logger함수를 이용할때 인자인 privacy는 기본으로 auto이고 privacy로 지정한 경우 디바이스로 빌드한 경우 interpolated string 혹은 커스텀 객체가 message에 포함된 경우에 민감한 정보일 수 있어서 시스템에서 자동으로 `<private>`으로 바꾸기때문에 그냥 출력시키고싶다면 `public`으로 수정

## References
[https://hereismyblog.tistory.com/31](url)

2024-06-13 11:55 UTC, ChoiysApple requested changes
`BaseViewController`에 로그 코드도 추가가 필요합니다!

2024-06-13 11:55 UTC, ChoiysApple commented on ShowPot/ShowPot/Common/LogHelper.swift
> +    private static let subsystem = Bundle.main.bundleIdentifier!
Force Unwrapping 지양해주세요

2024-06-14 04:47 UTC, dlrjswns commented on ShowPot/Podfile.lock
아 그래서 계속 저게 떴던거군요 ?? 아니 이전 PR부터 계속 뜨길래 저 때문인지 알고 이걸 그대로 커밋해도되나 고민했어요 ㅋㅋㅋㅋㅋㅋ

2024-06-14 04:50 UTC, dlrjswns commented on ShowPot/ShowPot/Common/LogHelper.swift
> +    private static let subsystem = Bundle.main.bundleIdentifier!
```suggestion
    private static let subsystem = Bundle.main.bundleIdentifier ?? ""
```
흠... 이 부분은 강제언래핑을 사용하지않는다면 그냥 위 코드처럼 수정하는게 좋을까요 ?

2024-06-14 05:27 UTC, dlrjswns commented
``` swift
[ShowPot/BaseViewController.swift:46] setupStyles() viewDidLoad() 호출
```
@ChoiysApple 지금 BaseViewController에 로그를 찍으니까 위에처럼 찍히는데 저는 LoginViewController가 찍히게끔 하고싶은데 
그럴려면 LoginViewController에서 로그를 찍어야할거같은데 그건 좀 비효율적일까요 ??

2024-06-14 14:15 UTC, ChoiysApple requested changes
지금 `develop` 커밋들이 `feature/#20-logger-dev` 브랜치에만 반영되어있어서, 제가 `viewConvention` 브랜치에 작업한 내용들도 해당 PR에서 보여지고 있습니다.

타겟 브랜치를 `develop`으로 바꾸시거나, `feature/#20-logger-master`도 rebase 완료해서 다시 PR 올려주세요

2024-06-14 14:15 UTC, ChoiysApple commented on ShowPot/ShowPot/Common/LogHelper.swift
> +    private static let subsystem = Bundle.main.bundleIdentifier!
해당 부분은 문제가 있어도 빈 스트링으로 나머지 동작들을 실행하게 되어서, 예기치 못한 사이드 이슈가 많이 발생할 여지가 있어보여요. 
‼️`subsystem` **변수가 아무거나 들어가도 상관없는지 여부가 제일 중요할 것 같습니다**

Bundle ID가 조회되지 않는 상황은, 명백히 잘못된 상황으로 보여서 해당 구문을 중단시켜 주는 것이 맞을 것 같습니다. `fatalError`를 이용하는 것도 한 방법입니다
```suggestion
    private static let subsystem: String?
    
    init() {
        guard let bundleID = Bundle.main.bundleIdentifier else {
            return 또는 fatalError("Error: Cannot find Bundle ID")
        }
    }
```

개인적으로는, 초기화가 필요한 변수가 있기 때문에 `static` 보다는 싱글톤이 나을 수도 있다는 생각이 드네요

2024-06-15 04:07 UTC, dlrjswns commented
> 지금 `develop` 커밋들이 `feature/#20-logger-dev` 브랜치에만 반영되어있어서, 제가 `viewConvention` 브랜치에 작업한 내용들도 해당 PR에서 보여지고 있습니다.
> 
> 타겟 브랜치를 `develop`으로 바꾸시거나, `feature/#20-logger-master`도 rebase 완료해서 다시 PR 올려주세요

아 넵 !! 타겟 브랜치를 logger-master -> develop 브랜치로 변경했습니다 !! 감사합니다 👍👍👍

2024-06-15 04:29 UTC, ChoiysApple commented on ShowPot/ShowPot/Common/Environment.swift
> +    static let bundleID: String = {
👍

2024-06-15 04:32 UTC, ChoiysApple approved these changes
<img src="https://github.com/YAPP-Github/24th-App-Team-3-iOS/assets/43776784/af33362b-1ebe-40d5-a366-cf8854b96e33" width="25%" alt="this was image">

2024-06-15 04:32 UTC, merged