[Feature] #37 폰트에 따른 letterSpacing, lineHeight값 조절을 위한 Extention함수 구현
YAPP-Github/24th-App-Team-3-iOS pull request #38
Opened 2024-06-28 02:48 UTC by dlrjswns

## Describe
- KRFont, ENFont인 경우에 따른 letterSpacing, lineHeight값 조절을 위한 함수 구현
- letterSpacing, lineHeight값을 커스텀할 수 있는 함수 구현

## Works made
- 텍스트에 따라 letterSpacing, lineHeight값을 조절해야했기에 이를 위한 함수가 필요하다 생각하여 구현
- 폰트에 따라서 일일이 letterSpcing, lineHeight값을 조절할 필요없이 함수사용만 하면 간편하게 적용하기위한 함수 구현

### As-Is

**기존 로직**
``` swift
let label = UILabel().then {
    $0.font = ENFont.H0
    let paragraphStyle = NSMutableParagraphStyle()
    paragraphStyle.lineHeightMultiple = 1.5

    let attributedString = NSAttributedString(
      string: "예시를 위한 라벨 텍스트",
      attributes: [
        .paragraphStyle: paragraphStyle
      ]
    )
    
    $0.attributedText = attributedString
}
```
- 기존에는 특정 폰트 별로 직접 letterSpacing, lineHeight값을 추가하고 attributedString을 일일이 작성해야함

### To-BE
**변경 로직**
``` swift
let label = UILabel().then {
    $0.font = ENFont.H0
    $0.text = "예시를 위한 라벨 텍스트"
    $0.setLineHeightAndLetterSpacingForFont()
}
```
- 간단한 함수작성으로 폰트 종류를 판별하여 함수내부에서 letterSpacing, lineHeight값 조절해줍니다.
- **반드시 예시 코드와 같이 `폰트와 텍스트 작성이후 함수를 실행`해야 올바르게 폰트에 따른 letterSpacing, lineHeight값을 조절하실 수 있습니다.**

## How to Test
- 위 변경된 코드처럼 폰트 적용 이후 함수를 사용하여 변경된 모습을 확인합니다.

## Issues Resolved
- #37 
## Additional context
- 반드시 예시 코드와 같이 폰트와 텍스트 작성이후 함수를 실행해야 올바르게 폰트에 따른 letterSpacing, lineHeight값을 조절하실 수 있습니다.

2024-06-28 02:49 UTC, dlrjswns commented
@ChoiysApple 
일단 지금 폰트에 따라 알아서 조절해주는 함수와 직접 값을 조절해줄 수 있는 함수를 따로 만들어두었는데 한번 코드보시고 어떻게 하는게 좋을지 알려주세요 !!

2024-06-28 14:37 UTC, ChoiysApple requested changes

2024-06-28 14:37 UTC, ChoiysApple commented on ShowPot/ShowPot/Common/Extension/UILabel+Extension.swift
> +    func setLineHeightAndLetterSpacingForFont() {
setLetterSpacing과 setLineHeight 메서드가 둘다 파라미터를 직접 받아서 받은 값을 정해주는거라, 이 메서드만 UILabel 내부값을 사용하는 방식은 일관성이 떨어지는 것 같습니다.

그리고 `KRFont`을 직접 사용하게 되면 확장성이 크게 떨어질 것 같아요.  상위 타입인`LanguageFont` 타입을 사용해야 합니다.

2024-06-28 14:37 UTC, ChoiysApple commented on ShowPot/ShowPot/Common/Extension/UILabel+Extension.swift
> +    func setLineHeight(lineHeightMultiple: CGFloat, string: String) {
`lineHeight` 값과 `letterSpacing` 값을 모두 설정해줄 일이 많은데, 
이런식으로 `setLineHeight(lineHeightMultiple: CGFloat, string: String)`, `setLetterSpacing(letterSpacingPercent: CGFloat, string: String)` 나눠두면 두 메서드 다 활용성이 떨어지는거 같네요.  (지금 코드에서도 이 두가지 로직이 합쳐진 메서드에서 이 둘을 안쓰고 있어요)

개인적으로 UILabel에 직접 정해주는 로직만 있는것 보다 `AttributedString`의 extension으로 만들어서 두 로직을 분리하는게 좋을 것 같네요

### 최대한 동작을 잘게 나누어서 이를 조합해 활용하는게 좋을 것 같아요!

2024-06-28 14:38 UTC, ChoiysApple commented
지금 사용하기엔 좋지만, 추후에 불필요한 코드가 되거나 확장성이 좋지 않을것 같은 부분이 있네요.
공수가 많이 들거나 너무 어렵다 싶으면 추후에 리팩토링 해도 괜찮을 것 같아요

2024-07-05 08:47 UTC, ChoiysApple requested changes
작업 완료하신 후에 정상 작동하는지 꼭 테스트하고 테스트한 내용을 첨부해주세요

이 작업같은 경우에는, 개발된 메서드 적용된 label / 미적용된 label 비교할 수 있게 화면에 출력해보고 스크린샷 & 테스트 할때 사용한 코드 첨부해 주세요

+ 수정하신 다음 `develop` 브랜치로 rebase 필요합니다.

2024-07-07 07:41 UTC, dlrjswns commented
@ChoiysApple 
기존 develop rebase에서 다시 푸시했고 PR메인에 attributed적용후, 적용전에 대한 스크린샷과 코드 첨부했습니다 !!
추가로 letterSpacing, lineHeight에 값 변경해서 제대로 동작하는것까지 확인했습니다 👍👍

2024-07-07 08:56 UTC, ChoiysApple commented on ShowPot/ShowPot/Common/Extension/NSMutableAttributedString+Extension.swift
> +extension NSMutableAttributedString {
@dlrjswns 
건준님 이부분 확인해주세요

2024-07-07 17:47 UTC, ChoiysApple requested changes

2024-07-07 17:47 UTC, ChoiysApple commented on ShowPot/ShowPot/Common/Extension/NSMutableAttributedString+Extension.swift
> +extension NSMutableAttributedString {
이부분 확인해주세요

2024-07-08 10:38 UTC, dlrjswns commented
@ChoiysApple NSMutableAttributedString -> NSAttributedString으로 변환작업완료했고 잘 동작하는지 값 바꿔서도 확인했습니다 !!

2024-07-08 11:27 UTC, ChoiysApple approved these changes
@dlrjswns 
수고하셨습니다~
지금 올라와있는 로그인 화면 코드가 이 PR에서 개발한 `setAttributedText` 메서드 사용 안하고 있다면  추가로 수정해주세요~

2024-07-08 11:27 UTC, merged