[OMLK-18] 소셜로그인 화면 UI 구성
YAPP-Github/24th-App-Team-3-iOS pull request #48
Opened 2024-07-08 10:26 UTC by dlrjswns

## Describe
- `Kakao`, `Google`, `Apple`에 관련된 화면 UI를 구현
- `Kakao`, `Google`, `Apple`에 관련된 소셜로그인 로직 구성(추후 소셜로그인에 필요한 값들 처리요망, TODO확인)

## Works made
- 소셜로그인에 필요한 로직들을 `LoginViewModel`에 작성하기위해 해당 함수 호출부분을 `LoginViewModel`에 작성
- `SocialLoginButton`클래스를 만들어 소셜로그인버튼을 커스텀하였음
- 소셜로그인에 필요한 이미지 에셋들을 추가하였음(`kakao`, `google`, `apple`)
- 소셜로그인화면내부에 있는 백버튼에 관련된 로직을 `coordinator`와 연동시켰음

## Changes Made
### To-BE

**변경 로직**
- 소셜로그인에 관련된 로직을 `LoginViewModel`에 이동
- 백버튼에 관련된 로직을 `LoginCoordinator`에 이동
- 소셜로그인 알림텍스트, `Google` & `Kakao` & `Apple` 제목텍스트 `SwiftGen`이용하여 리소스화

**스크린샷**
<iPhone 15 Pro Max화면>
<img src="https://github.com/YAPP-Github/24th-App-Team-3-iOS/assets/39263235/902713c2-937d-4044-9187-0d6534105af9" width="25%" alt="Image">

* <iPhone SE 3세대화면>
<img src="https://github.com/YAPP-Github/24th-App-Team-3-iOS/assets/39263235/7c51985e-ace5-4bf7-9348-da447bab16a2" width="25%" alt="Image">

## How to Test
``` swift
let navigationController = UINavigationController()
let coordinator = LoginCoordinator(navigationController: navigationController)
window.rootViewController = navigationController
coordinator.start()
```
* `SceneDelegate`에서 위 코드로 변경하여 소셜로그인화면을 확인
* `Kakao`, `Google`, `Apple` 소셜로그인 버튼을 클릭해 클로저 혹은 Delegate로 값이 들어오는지 확인

## Issues Resolved
- #OMLK-18

## Additional context
- @ChoiysApple TODO확인해주시고 이후 소셜로그인 관련 clientID, 애플 일부 로직 해결 필요

## References
[카카오톡 소셜로그인 iOS 문서](https://developers.kakao.com/docs/latest/ko/kakaologin/ios)
[구글 소셜로그인 iOS 문서](https://firebase.google.com/docs/auth/ios/google-signin?hl=ko)
[애플 소셜로그인 문서](https://developer.apple.com/kr/sign-in-with-apple/get-started/)

2024-07-08 10:51 UTC, KakaoTocs commented
(리뷰는 할 예정입니다!)
앞으로 리뷰를 받다 보면, 리뷰 내용이 대건님이랑 저랑 다를 수 있어요
그런 상황에서는 같이 작업하는 대건님 의견을 중심으로 봐 주시면 좋을거 같아요. 🙇‍♂️

2024-07-08 11:17 UTC, KakaoTocs commented on ShowPot/ShowPot/Presentation/Scene/Login/LoginViewHolder.swift
> +    final class SocialLoginButton: UIView {
**C**
다른 컴포넌트면 파일 분리해도 괜찮을거 같아요

2024-07-08 11:19 UTC, KakaoTocs commented on ShowPot/ShowPot/Presentation/Scene/Login/LoginViewModel.swift
> +        )
**C**
let didTappedGoogleLoginButton = input.didTappedGoogleLoginButton.map { SocialLoginType.google }
let didTappedAppleLoginButton = input.didTappedGoogleLoginButton.map { SocialLoginType.apple }
let didTappedKakaoLoginButton = input.didTappedGoogleLoginButton.map { SocialLoginType.kakao }

Observable.merge(
    didTappedGoogleLoginButton,
    didTappedAppleLoginButton,
    didTappedKakaoLoginButton
)
이렇게 변수로 빼서 사용하면 보기 더 좋을거 같아요 (네이밍은 따로 지어 주세요)

2024-07-08 11:19 UTC, KakaoTocs commented on ShowPot/ShowPot/Presentation/Scene/Login/LoginViewModel.swift
> +            }
**C**
메서드로 뽑아서 호출하면 좋을거 같습니다.

2024-07-08 11:21 UTC, KakaoTocs commented on ShowPot/ShowPot/Presentation/Scene/Login/LoginViewModel.swift
> +}
**C**
nested 형태의 타입이 아니라면 파일 분리 하는게 어떨까 싶네요?

2024-07-08 11:21 UTC, KakaoTocs approved these changes

2024-07-08 11:22 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Login/LoginViewHolder.swift
> +    final class SocialLoginButton: UIView {
@ChoiysApple 대건님 이 부분 ShowPot -> Common -> UI -> Login폴더 만들어서 사용할까요 ??
아니면 Presentation -> Common에서 Login폴더 만들어서 추가할까요 ?

2024-07-08 11:24 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Login/LoginViewModel.swift
> +            }
아 하나의 함수에 SocialLoginType을 인자로 받아서 처리하면 좋을꺼같다는 말씀이신가요 ??

2024-07-08 11:26 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Login/LoginViewModel.swift
> +}
좋은거같아요 !! 대건님 위에 특정 화면안에서 사용하는 UI나 이런 Type같은 경우는 어떤식으로 파일을 두면 좋을까요 ??

2024-07-08 11:31 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Login/LoginViewModel.swift
> +    }
@KakaoTocs 진우님 개인적으로 궁금한점이 있는데 소셜로그인에 대한 로직을 LoginViewController보다 LoginViewModel에 두는게 옳다고 생각하여 구현했는데 LoginViewModel에서 구현하니 구글소셜로그인처럼 LoginViewController를 인자로 넣어야하는 부분에서 guard let 구문으로 최상단 화면을 가져오는 로직이 추가되었는데 진우님이라면 해당 부분을 LoginViewModel에서 구현하실꺼같은지 궁금합니다 !!

2024-07-08 17:03 UTC, KakaoTocs commented on ShowPot/ShowPot/Presentation/Scene/Login/LoginViewModel.swift
> +            }
네, 저는 웬만하면 subscribe, bind에서 로직을 짜지 않고, 메서드를 호출 하도록 하고 있어요 (물론 잘 못 지키기도..)

2024-07-08 17:10 UTC, KakaoTocs commented on ShowPot/ShowPot/Presentation/Scene/Login/LoginViewModel.swift
> +    }
일단 라이브러리 한계상 최상위 화면 위에 구글 로그인 화면을 띄우기 위해 UIViewController를 받고 있어요.
그래서 저는 해당 로직을 Service로 class를 분리하고, 인자로 UIViewController를 받아서 호출 할때 그대로 전달하는 형태로 할 거 같아요.
라이브러리 특성상 비즈니스 로직(ViewModel)에서 뷰(ViewController)를 참조하는 거는 불가피한 상황이라고 생각해요(= 예외 사항..)

그런데 혹시 rootViewController말고, 현재 화면을 넣어주면 동작 안하나요??
rootViewController랑 현재 화면이랑 같을거 같아서요

2024-07-09 02:15 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Login/LoginViewModel.swift
> +    }
아 rootViewController넣어줘도 올바르게 동작합니다 !! 다만 해당 부분은 반드시 로그인화면위에서 동작해야하기때문에 저 조건문을 추가했던거같아요 !! 그냥 지우는게 좋을까요 ??

2024-07-09 02:17 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Login/LoginViewModel.swift
> +            }
좋은거같아요 !! 처음 코드작성할때 하나의 함수로 짰었는데 로직을 분리하는게 좋을꺼같다는 생각에 저리 짠거긴합니다 🧐🧐
말씀하신대로 수정해볼게요 !!

2024-07-09 15:31 UTC, ChoiysApple requested changes
이번엔 코멘트 내역이 좀 많네요 😅
저희 지금 일정이 좀 밀려있어서, 부지런히 수정해주세요~

앗 그리고 브랜치 네이밍에 `feature` 가 안붙어있네요! 브랜치 이름도 가능하면 바꿔주세요

다만 공통 모듈인 행각/자간 작업 우선적으로 끝내주세요
- #37

2024-07-09 15:31 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Login/LoginViewHolder.swift
> +                    socialLoginImageView.image = UIImage(resource: .kakao)
상기한 `.google`과 동일합니다.

2024-07-09 15:31 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Login/LoginViewHolder.swift
> +                    socialLoginImageView.image = UIImage(resource: .apple)
상기한 .google과 동일합니다.

2024-07-09 15:31 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Login/LoginViewHolder.swift
> +                    socialLoginDescriptionLabel.textColor = .white
`UIColor.white` 색상을 사용하면 다크모드일 때 색상이 검정색으로 변경됩니다.
#44 에서 같이 수정할게요. `// TODO: #44 애셋 네이밍 변경 이후 작업 필요` 달아주세요

2024-07-09 15:31 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Login/LoginViewHolder.swift
> +        private let containerView = UIStackView().then {
어떤 컴포넌트를 담고 있는 Container라는지 알기 힘든 네이밍입니다.
네이밍 수정이 필요합니다. 스택뷰이니 만큼 `stack` 이라는 단어가 들어가면 좋을 것 같아요

2024-07-09 15:31 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Login/LoginViewHolder.swift
> +    final class SocialLoginButton: UIView {
`UIButton`을 사용하지 않은 이유가 있나요?
`이미지` + `텍스트`가 나란히 배치되는 UI는 기본 컴포넌트만으로 충분히 구현 가능해요

[How to position an UIButton image to the right side of the text](https://sarunw.com/posts/how-to-position-uibutton-image-to-th-right-side-of-text.md/)

2024-07-09 15:31 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Login/LoginViewHolder.swift
> +            }
1. `containerView`와 `button`의 레이아웃 구성 방식이 좀 어색한거 같네요
    1.1. 컨테이너 뷰가 버튼의 subview가 되는게 이해하기 쉽지 않나요?
    1.2. 버튼을 터치 이벤트로만 사용할 거라면, UIGestureRecognizer를 사용하여 불필요한 뷰를 줄일 수 있습니다
    1.3. 이런 방식이라면, 부모뷰가 `UIView`가 아니라 `UIButton`이어도 좋지 않을까요?
2. 버튼의 Y 축에 대한 레이아웃이 잡히지 않았습니다. 
    2.1. UI가 수직 방향으로 이상하게 잡힐 수 있습니다
    2.1. 버튼이 뷰보다 커질 수 있습니다.

2024-07-09 15:31 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Login/LoginViewHolder.swift
> +                    backgroundColor = .yellow
카카오 배경색 이 색상 아니에요 `#FEE500` 입니다. 수정해주세요

디자인 가이드에서 색상이 비슷해보여도 시스템 기본 컬러는 사용 지양해주세요

2024-07-09 15:31 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Login/LoginViewHolder.swift
> +                    backgroundColor = .white
이 색상 다크모드 변경되면 검은색됩니다. 컬러값 따로 만들어서 수정해주세요
참고로 `white` `mainwhite` 같은 네이밍이 아니라, `google_white` 처럼 구글에서 사용하는 흰색이라는 네이밍이어야 합니다

2024-07-09 15:31 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Login/LoginViewModel.swift
> +        )
세가지 이벤트를 merge를 통해 한번에 받아오더라도, `SocialLoginType`에 따라서`loginWithGoogle()` `loginWithApple()` `loginWithKakao()` 로 다시 분기처리 되기 때문에 큰 의미가 없는거 같네요

merge 없이 observerble들을 따로 subscribe하거나, 각 소셜 버튼의 입력은 하나의 observarble로 처리하되, 각각 다른 `SocialLoginType`를 `emit`하도록 리팩토링 하는게 좋을 것 같아요

2024-07-09 15:31 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Login/LoginViewModel.swift
> +}
이런 부분들 `UseCase`로 분리하는게 좋을 것 같긴 한데, 공수가 좀 필요할 것 같으니 일단 여기에 두는게 좋을 것 같아요.

`TODO` 코멘트만 남겨놔주세요~

2024-07-09 15:31 UTC, ChoiysApple commented on ShowPot/ShowPot/Resource/Localizable/Localizable.strings
> +"socialLogin_apple_title" = "Apple로 시작하기";
버튼에 사용될 텍스트는 `button` 이름이 들어가는게 좋을 것 같아요

2024-07-09 15:35 UTC, KakaoTocs commented on ShowPot/ShowPot/Presentation/Scene/Login/LoginViewModel.swift
> +    }
rootViewController를 최대한 사용 안 하는 의도로 질문한거에요
현재 viewController에 띄우는게 동작하면 이렇게 하는게 좋을거 같아서요

2024-07-09 15:41 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Login/LoginViewController.swift
> +        _ = viewModel.transform(input: input)
오 너무 좋습니다 !! 바로 수정하겠습니다 👍

2024-07-09 15:44 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Login/LoginViewController.swift
> +      return view.window!
네 맞습니다 !! 아래 애플 로그인관련된 공식문서 확인해보시면 저런식으로 구현되어있습니다 !!

[Apple 로그인관련 개발 문서 링크](https://developer.apple.com/documentation/sign_in_with_apple/implementing_user_authentication_with_sign_in_with_apple)

2024-07-09 15:45 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Login/LoginViewController.swift
> +extension LoginViewController: ASAuthorizationControllerDelegate {
아 넵 알겠습니다 !! 소셜로그인마다 혼선이 있을 수 있겠군요 🧐🧐 Delegate에 대한 설명 주석으로 달아놓겠습니다

2024-07-09 15:54 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Login/LoginViewHolder.swift
> +            _ = [socialLoginImageView, socialLoginDescriptionLabel].map { containerView.addArrangedSubview($0) }
1. `map`고차함수를 사용했기에 리턴되는 시퀀스가 있지만 사용하지않으므로 경고문을 발생시키지않기위해 사용하였습니다.
2. 저 상황에서 사용할 수 있는 함수가 `forEach`와 `map`으로 알고있는데 사실 이전 프로젝트에서 `map`함수가 무의미할 정도로 미미하지만 빠르다고 인지하고있어서 `map`으로 했습니다만 찾아보니 `forEach`가 1번에 대한 불필요한 코드도 줄일 수 있고 부수적인 부분을 처리하는점에서 애플에서 권장하는 의미에 부합하는거같습니다, 저 부분 `forEach`로 수정해놓겠습니다 !!

2024-07-09 15:57 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Login/LoginViewHolder.swift
> +        $0.layoutMargins = .init(top: .zero, left: 16, bottom: 56, right: 16)
저 궁금한점이 `isLayoutMarginsRelativeArrangement`값을 `true`로 변경하게되면은 `layoutMargins`값을 주지않을때에 view 하단 `safeLayoutGuide`에 맞춰지지않나요 ??

2024-07-09 15:57 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Login/LoginViewHolder.swift
> +        $0.setImage(UIImage(resource: .icArrow36Left).withTintColor(.white), for: .normal)
아 넵 확인했습니다 !! 추가해놓겠습니다

2024-07-09 15:59 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Login/LoginViewHolder.swift
> +                    socialLoginDescriptionLabel.textColor = .white
대건님 그 제가 지금 시뮬레이터를 다크모드로 변경해서 디버깅하고있는중인데 해당 라벨텍스트에 대한 색상이 올바르게 보이는거같은데 실기기에서는 달라지는건가요 ??

2024-07-09 16:00 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Login/LoginViewHolder.swift
> +        private let containerView = UIStackView().then {
아 `containerStackView`라는 이름으로 네이밍 수정해놓겠습니다 !!

2024-07-09 16:01 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Login/LoginViewHolder.swift
> +                    backgroundColor = .yellow
아 이 부분도 자간 행간 PR이 Merge된 이후에 attribute추가하면서 해놓으려했는데 바로 해당 부분 처리하는 커밋추가해놓았습니다 !!

2024-07-09 16:06 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Login/LoginViewHolder.swift
> +                    socialLoginImageView.image = UIImage(resource: .google)
엇 이 부분 처음 알았네요 ㅋㅋㅋㅋㅋㅋ 바로 수정하도록 하겠습니다 👍👍

2024-07-09 16:22 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Login/LoginViewHolder.swift
> +    final class SocialLoginButton: UIView {
오 해당 레퍼런스 참고해서 오늘안에 바로 수정해서 올려드릴게요 !!

2024-07-09 16:25 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Login/LoginViewHolder.swift
> +            }
button을 따로 뺐던 이유는 이후에 터치영역에 대한 변경이 일어나도 button에 관련된 레이아웃만 바꾸면 손쉽게 변경할 수 있을꺼라 생각해서 한거긴한데 앞 comment남겨주신것처럼 UIButton을 상속받게하여 수정해보도록 하겠습니다 !!

2024-07-09 16:28 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Login/LoginViewModel.swift
> +        )
음 헌데 각각의 다른 소셜로그인버튼에 대한 로직을 구분해주기위해서는 대건님이 언급하신것처럼 버튼Input에 대해 하나하나 subscribe하거나 저처럼 SocialLoginType을 지정해주거나인데 하나하나 subscribe하게되면 각각의 소셜로그인버튼Input에 대한 불필요한 코드가 추가된다고 생각하는데 어차피 SocialLoginType으로 매핑해서 사용할꺼라면 merge를 이용하는게 깔끔하지않을까요 ??

2024-07-09 16:29 UTC, dlrjswns commented on ShowPot/ShowPot/Resource/Localizable/Localizable.strings
> +"socialLogin_apple_title" = "Apple로 시작하기";
아 이 부분도 네이밍 변경해놓겠습니다 !!

2024-07-09 16:42 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Login/LoginViewHolder.swift
> +                    backgroundColor = .white
google_white로 추가하여 수정해놓았습니다 !!

2024-07-09 17:15 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Login/LoginViewModel.swift
> +    }
아아 질문의 의도를 잘못 파악했어요 !! 그 지금 LoginViewModel내부에서 현재 viewController를 어떤식으로 가져올 수 있을까요 ??

2024-07-10 01:00 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Login/LoginViewHolder.swift
> +        $0.layoutMargins = .init(top: .zero, left: 16, bottom: 56, right: 16)
1. 말씀드렸다시피, 스택뷰가 보이는 부분보다 불필요하게 커지게 됩니다. 만약 버튼이나 라벨이라도 아래쪽에 추가되면 수정이 힘들어질 수 있습니다. 
2. 스택뷰가 보이는 것 보다 과하게 크다면, 나중에 다른 사람이 이 부분을 수정할 때 이해하기 힘듭니다.
3. 다른 부분은 모두 constraint로 간격을 설정했는데, 이 부분만 다르게 간다면 코드 이해가 어려울 수 있습니다

2024-07-10 01:02 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Login/LoginViewHolder.swift
> +                    socialLoginDescriptionLabel.textColor = .white
네 전 달라졌었어서 수정하고 이슈 올렸어요
그리고 디자인 시스템에도 흰색이 명시되어 있어서 따로 지정하는게 맞습니다. 색상값이 조금이라도 달리지면 힘들어요

2024-07-10 01:03 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Login/LoginViewHolder.swift
> +                    backgroundColor = .yellow
나중에 처리하려는 부분이 있다면 꼭 todo 달아주세요

2024-07-10 01:10 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Login/LoginViewModel.swift
> +        )
따로 subscribe하면 `SocialLoginType`을 이용할 필요가 없습니다. 

그리고 이미 각 로그인 유형마다 로그인 처리 로직에서 공통되는 코드가 없기 때문에 코드 양이나 반복은 비슷해요

2024-07-10 05:31 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Login/LoginViewHolder.swift
> +        $0.layoutMargins = .init(top: .zero, left: 16, bottom: 56, right: 16)
오호 알겠습니다 !! 그렇다면 bottom부분을 SuperView의 constraints를 이용해서 수정하도록 하겠습니다 !!

2024-07-10 05:33 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Login/LoginViewHolder.swift
> +                    socialLoginDescriptionLabel.textColor = .white
아 정말요 ?? 여태 system관련 색상만 어떤 모드냐에 따라서 달라지는줄 알았는데 신기하네요
넵 알겠습니다, TODO 달아놓을게요 !!

2024-07-10 05:34 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Login/LoginViewHolder.swift
> +                    backgroundColor = .yellow
넵 대건님덕분에 하나 더 알아갑니다 !! 앞으로는 함께 개발하는 대건님을 배려해볼게요 👍👍👍

2024-07-10 05:36 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Login/LoginViewModel.swift
> +        )
아 만약에 로그인 유형마다 따로 subscribe하게되면 disposed하는 코드가 한번 더 추가된다 생각하였고 이후에 소셜로그인 API호출할때 loginType도 받는다는걸로 알고있어서 merge를 해야 코드가 깔끔해진다고 생각했어요 !!

일단 대건님 말씀대로 하나하나 subscribe해서 다시 커밋올리도록 하겠습니다 👍👍👍

2024-07-10 05:46 UTC, dlrjswns commented
@ChoiysApple 일단 대건님이 올려주신 코멘트들은 전부 반영을 하였고 #37 관련된 baseOffLine부분을 얼른 수정하고 다시 올려드릴게요, 지금 그 부분이 레퍼런스대로 잘 안되는거같아서요 😭😭😭

2024-07-10 12:08 UTC, ChoiysApple requested changes
자잘하게 검토할 부분이 약간 남아있지만 마지막 리뷰가 될 것 같네요
마지막으로 검토 부탁드립니다!

2024-07-10 13:01 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Login/CustomView/SocialLoginButton.swift
> +            configuration.baseForegroundColor = .white
아 지금 저 부분 위에 이미 baseForegroundColor로 지정했는데 한번더 지정된 코드네요 !! 삭제하도록 하겠습니다

2024-07-10 13:01 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Login/CustomView/SocialLoginButton.swift
> +            attributedTitle = AttributedString(Strings.socialLoginGoogleButton)
넵 attributedString에 해당하는 부분 추가했습니다 !!

2024-07-10 13:11 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Login/CustomView/SocialLoginButton.swift
> +    private func setupStyles() {
UIButton+Configuration을 설정하는 작업과 AttributedString을 설정하는 작업을 분리하여 커밋올렸습니다 !!

2024-07-10 15:01 UTC, ChoiysApple approved these changes
메서드 이름이랑 동작이 좀 안맞는 부분이 있긴 한데
크게 문제되는 부분도 아니고, 시간 지체도 많이 되어서 머지하겠습니다

2024-07-10 15:01 UTC, merged