[Feature] #37 소셜로그인 화면 자간 및 줄높이 적용
YAPP-Github/24th-App-Team-3-iOS pull request #59
Opened 2024-07-11 17:21 UTC by dlrjswns

## Describe
- #54 다음 이슈해결로 인한 소셜로그인화면에 해당하는 텍스트에 자간 및 줄 높이 적용

## Works made
- 라벨로 구성되어있는 부분은 `setAttributedText`함수를 이용하여 자간 및 줄 높이를 적용
- `UIButton.Configuration`으로 구성되어있는 `SocialLoginButton`에서는 텍스트가 `AttributedString`으로 구현되어있어 라벨에 `setAttributedText`를 적용한 이후 `attributedText`를 가져와 `configuration`에 적용

## Changes Made

### As-Is

**기존 로직**
``` swift
/// alertLabel not Changed Logic
let alertLabel = UILabel().then {
        $0.textColor = .white
        $0.font = KRFont.H2
        $0.text = Strings.socialLoginDescription
        $0.textAlignment = .center
}

/// SocialLoginButton not Changed Logic
var attributedTitle: AttributedString
attributedTitle = AttributedString(Strings.socialLoginGoogleButton)
attributedTitle.font = KRFont.H2
return attributedTitle
```
- 기존에는 `AttributedString`, `UILabel+text`를 이용해 단순 폰트와 텍스만을 지정(자간 및 줄 높이 지정 X)

**스크린샷**
|기존 자간 및 줄 높이가 적용되지않은 화면|
|:--:|
|<img src="https://github.com/YAPP-Github/24th-App-Team-3-iOS/assets/39263235/be92fe2d-7f70-4df1-96b6-534f0ba3bba3" width="25%" alt="Image">

### To-BE

**변경 로직**
``` swift
/// alertLabel Changed Logic
let alertLabel = UILabel().then {
        $0.textColor = .white
        $0.font = KRFont.H2
        $0.setAttributedText(font: KRFont.self, string: Strings.socialLoginDescription)
        $0.textAlignment = .center
}

/// SocialLoginButton Changed Logic
let buttonTitleLabel = UILabel()
buttonTitleLabel.setAttributedText(font: KRFont.self, string: Strings.socialLoginGoogleButton)
if let attributedText = buttonTitleLabel.attributedText {
        var attributedString = AttributedString(attributedText)
        attributedString.font = KRFont.H2
        return attributedString
}
```
- UILabel에 대한 자간 및 줄 높이는 `setAttributedText`함수를 이용해 구현
- UIButton.Configuration의 텍스트는 단순 라벨을 가지고 적용할 수 없어 임의의 라벨에 `setAttributedText`함수를 통해 적용 이후 `attributedText`를 이용해 `configuration`에 넣어주었음

**스크린샷**
|자간 및 줄 높이만 적용된 화면|
|:--:|
|<img src="https://github.com/YAPP-Github/24th-App-Team-3-iOS/assets/39263235/abd7bb18-c0e9-42f7-ae82-187b3e2d3e3c" width="25%" alt="Image">

|자간 및 줄 높이, baselineOffset적용된 화면|
|:--:|
|<img src="https://github.com/YAPP-Github/24th-App-Team-3-iOS/assets/39263235/561a5e5a-1277-40b3-912f-dc32c9e5c33a" width="25%" alt="Image">

## How to Test

``` swift
let navigationController = UINavigationController()
let coordinator = LoginCoordinator(navigationController: navigationController)
window.rootViewController = navigationController
coordinator.start()
```
- 위 코드를 `SceneDelegate`에 삽입하여 소셜로그인화면에 존재하는 텍스트를 확인
- `setAttributedText`내부의 lineHeight, letterSpacing, baselineOffset을 변경하여 올바르게 적용되는지 확인

## Issues Resolved
- #37

2024-07-12 02:28 UTC, ChoiysApple requested changes

2024-07-12 02:28 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Login/CustomView/SocialLoginButton.swift
> +    private func setButtonAttributedString(with type: SocialLoginType) -> AttributedString? {
이 메서드는 `set` 이라는 네이밍을 가지고, 실제로 `buttonTitleLabel.setAttributedText(font: KRFont.self, string: Strings.socialLoginGoogleButton)` 동작을 통해서 문구를 넣어주는 동작을 하고 있는데, `AttributedString`을 반환하는 이유가 있나요?

2024-07-12 02:28 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Login/CustomView/SocialLoginButton.swift
> +        return nil
버튼의 attributedText를 반환하기 위해서 이 구문이 있는거 같은데,
이 부분이 왜 필요한가요?

해당 값을 사용하기 위해 반환이 필요하더라도, 함수 하나에 두가지 다른 일을 하고 있기 때문에 부적절합니다

2024-07-12 04:24 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Login/CustomView/SocialLoginButton.swift
> +    private func setButtonAttributedString(with type: SocialLoginType) -> AttributedString? {
`UIButton.Configuration`에서 내부 라벨에 텍스트를 직접 넣어주는것이아닌 `attributedText`를 통해서 전달해야했어요, 그렇기에 필요한 `AttributedString`타입을 반환하는 작업을 하고있다생각하여 `set`이라는 네이밍을 가지고 작업하였고 `SocialLoginType`에 따라서 다른 값을 반환해주어야했기에 인자로 생성하였습니다.

내부에서 attributedText를 추출하는 동작과 AttributedString을 반환하는 동작이 존재해서 혼동이 있는것같네요, 이 부분 나눠보겠습니다.

2024-07-12 04:30 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Login/CustomView/SocialLoginButton.swift
> +        return nil
저 부분이 필요한 이유는 `UIButton.Configuration`을 사용하고있어서 `titleLabel`을 통해 `setAttributedText`함수를 적용할 수 없었어요, 그렇기때문에 `AttributedString`을 사용해야만 했기에 자간 및 줄높이, baseLineOffset값을 적용한 라벨을 만들어 이에 대한 `attributedText`를 추출해 `AttributedString`을 생성한 용도로 사용했습니다

위에 코멘트 달았던 부분처럼 동작에 맞는 함수의 이름으로 나눠보겠습니다

2024-07-12 05:08 UTC, dlrjswns commented
@ChoiysApple 
<수정사항>
1. 기존 `set`이라고 정의한 함수의 동작이 직접적으로 UIButton의 값을 적용한다기보다는 UIButton을 위한 값을 가져오는 행위가 올바른 표현이라 생각하여 `get`이라는 네이밍으로 수정하였습니다
2. 자간, 줄높이, baseLineOffset값을 라벨에 적용하고 `attributedText`를 통해 받아온 값으로 AttributedString을 반환하는 두가지 동작이 포함되어있어서 이를 `configureLabelAttributedText`, `getButtonAttributedString`의 이름을 가진 함수로 구분지어줬습니다

2024-07-12 05:21 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Login/CustomView/SocialLoginButton.swift
> +    private func setButtonAttributedString(with type: SocialLoginType) -> AttributedString? {
네 확인 다시해보니 현재동작 기준으로는 return해주는게 필요하네요. 
메서드를 나눈 것 자체는 좋으나, 잘못된 부분으로 나뉘어서 불필요하게 데이터가 오고 가는 것 같네요

지금 계속 데이터 입력 부분에서 로직이 복잡하고 문제가 생기고 있어요. 원인을 생각해보면 `리소스 적용` 부분과 `뷰 UI 설정` 부분이 혼재되어 있어서 그런거 같네요. 
1. `배경색` `테두리 색상` `이미지` `텍스트 컬러` `텍스트 문구` 을 매개변수로 받아 `Configuration`을 설정하는 부분
2. 1에서 개발한 메서드에 필요한 리소스를 넣어주는 부분

이렇게 두가지로 나누어서 로직 분리하는게 좋을 것 같네요

2024-07-12 05:26 UTC, ChoiysApple commented
> @ChoiysApple <수정사항>
> 
> 1. 기존 `set`이라고 정의한 함수의 동작이 직접적으로 UIButton의 값을 적용한다기보다는 UIButton을 위한 값을 가져오는 행위가 올바른 표현이라 생각하여 `get`이라는 네이밍으로 수정하였습니다
> 2. 자간, 줄높이, baseLineOffset값을 라벨에 적용하고 `attributedText`를 통해 받아온 값으로 AttributedString을 반환하는 두가지 동작이 포함되어있어서 이를 `configureLabelAttributedText`, `getButtonAttributedString`의 이름을 가진 함수로 구분지어줬습니다

일단 방금전에 코멘트 하나 남겨드렸는데, 확인해보시고 수정 가능할것 같으면 진행해주세요
작업 어떻게 할지 감이 안오시면 나중에 제가 리팩토링해서 보여드릴게요

2024-07-12 05:45 UTC, ChoiysApple requested changes
다시 요청해주세요~

2024-07-12 05:51 UTC, dlrjswns commented
> > @ChoiysApple <수정사항>
> > 
> > 1. 기존 `set`이라고 정의한 함수의 동작이 직접적으로 UIButton의 값을 적용한다기보다는 UIButton을 위한 값을 가져오는 행위가 올바른 표현이라 생각하여 `get`이라는 네이밍으로 수정하였습니다
> > 2. 자간, 줄높이, baseLineOffset값을 라벨에 적용하고 `attributedText`를 통해 받아온 값으로 AttributedString을 반환하는 두가지 동작이 포함되어있어서 이를 `configureLabelAttributedText`, `getButtonAttributedString`의 이름을 가진 함수로 구분지어줬습니다
> 
> @dlrjswns 일단 방금전에 코멘트 하나 남겨드렸는데, 확인해보시고 수정 가능할것 같으면 진행해주세요 작업 어떻게 할지 감이 안오시면 나중에 제가 리팩토링해서 보여드릴게요 일단 리뷰는 다시 request change 처리 해둘테니, 확인 끝나면 다시 요청해주세요

아 코멘트 참고해서 수정 반드시 제가 해보겠습니다, 천천히 고민해볼게요 👍👍

2024-07-16 13:31 UTC, ChoiysApple requested changes
버튼 configuration 부분들은 어차피 리팩토링 될거라 참고만 해 두시고,
나머지 코멘트만 수정 진행해주세요

2024-07-16 13:31 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Login/CustomView/SocialLoginButton.swift
>          configuration.attributedTitle = attributedTitle
`createButtonConfiguration(with: type)`에서 `NSAttributedString`을 매개변수로 받아 처리하면 코드라인이 줄어들 것 같아요
```suggestion
        let attributedTitle = configureButtonAttributedString(with: type)
        let configuration = createButtonConfiguration(with: type, text: attributedTitle)
```

2024-07-16 13:31 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Login/CustomView/SocialLoginButton.swift
> +     지정된 속성으로 구성된 `UIButton.Configuration` 객체를 반환합니다.
해당 메서드의 동작 자체가 상당히 직관적이라, 주석 없이 네이밍 만으로 충분할 것 같네요.

2024-07-16 13:31 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Login/CustomView/SocialLoginButton.swift
> +    private func configureButton(baseBackgroundColor: UIColor, baseForegroundColor: UIColor, image: UIImage, strokeWidth: CGFloat? = nil, strokeColor: UIColor? = nil) -> UIButton.Configuration {
저희가 코딩 컨벤션을 엄청 엄격히 지키지는 않지만, 이렇게 파라미터가 많은 경우에는 정리가 필요할 것 같아요 -> [줄바꿈](https://github.com/YAPP-Github/24th-App-Team-3-iOS/pull/59/files#%EC%A4%84%EB%B0%94%EA%BF%88) 참고

`configure`이라는 네이밍 자체가 버튼에 직접 접근해 수정하는 느낌이라, `UIButton.Configuration`을 반환하는 현재 동작과는 약간 안맞는것 같기도(?) 합니다. (근데 이렇게 사용하는 사례가 많긴 해서 큰 문제는 없을것 같네요)

그리고 이 동작은 여기보단 `UIButton`의 `extension`에 들어가면 좋을 듯 한데, 어차피 제가 커스텀 UI로 리팩토링 할 생각이라 그때 제가 옮겨놓는 걸로 하겠습니다

2024-07-16 13:31 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Login/CustomView/SocialLoginButton.swift
>          }
해당 값들의 기본값이 0.0이기 때문에, nil coalescing 사용해서 처리하면 가독성이 좋을 것 같네요

@KakaoTocs 
nil coalescing이 좀 느리다고 들은거 같은데, 혹시 아시는거 있나용

2024-07-16 13:31 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Login/CustomView/SocialLoginButton.swift
> +    private func configureLabelAttributedText(for type: SocialLoginType) -> UILabel {
위와 비슷하게 `configure`네이밍에 대해 고민해 볼 필요가 있을 것 같아요

2024-07-16 13:31 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Login/CustomView/SocialLoginButton.swift
>          }
사용 문구 제외하고는 `SocialLoginType` 별로 동작이 동일해서 비효율적인것 같네요

2024-07-16 13:31 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Login/CustomView/SocialLoginButton.swift
> +        guard let attributedText = labelWithAttributedText.attributedText else { return nil }
이 부분에서 else 구문으로 넘어가게 된다면, 앱에는 아무런 텍스트가 표시되지 않습니다.
작성하신 코드 구조 자체에서 오는 문제인데, 위에 남긴 코멘트랑 같이 생각해보시면 될거같네요

2024-07-16 13:49 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Login/CustomView/SocialLoginButton.swift
> +    private func configureButton(baseBackgroundColor: UIColor, baseForegroundColor: UIColor, image: UIImage, strokeWidth: CGFloat? = nil, strokeColor: UIColor? = nil) -> UIButton.Configuration {
오호 어떤걸 기준으로 커스텀하실지 궁금하네요, 다음에 PR올려주시면 확인해보겠습니다 👍
혹시 줄바꿈링크가 애매하게 돼서 그런데 파라미터가 많은 경우에 현재 configureButton을 작성할때와 같이 인자마다 띄어놓자는 말씀이신가요 ?

2024-07-16 13:50 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Login/CustomView/SocialLoginButton.swift
>          configuration.attributedTitle = attributedTitle
넵 바로 수정해볼게요 !

2024-07-16 14:10 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Login/CustomView/SocialLoginButton.swift
> +    private func configureLabelAttributedText(for type: SocialLoginType) -> UILabel {
setup과 create를 이용해서 수정해두겠습니다 !

2024-07-16 14:13 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Login/CustomView/SocialLoginButton.swift
> +        guard let attributedText = labelWithAttributedText.attributedText else { return nil }
@ChoiysApple 
SocialLoginType에 대해 반드시 attribute를 적용받기때문에 attributedText에 대한 리턴값이 nil이 나오진않아 강제언래핑으로 코드를 수정하는건 어떨까요 ?

2024-07-16 14:14 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Login/CustomView/SocialLoginButton.swift
>          }
엇 이 부분은 전에 대건님이 말한 부분과 비슷한 코드같네요, 한번 수정해볼테니 확인해주세요 !!

2024-07-16 23:03 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Login/CustomView/SocialLoginButton.swift
> +    private func configureButton(baseBackgroundColor: UIColor, baseForegroundColor: UIColor, image: UIImage, strokeWidth: CGFloat? = nil, strokeColor: UIColor? = nil) -> UIButton.Configuration {
네 인자가 너무 많아지면 다음줄오 들여쓰기 하는거요

2024-07-16 23:05 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Login/CustomView/SocialLoginButton.swift
>          }
@dlrjswns 
강제언래핑 절대 안됩니다

2024-07-17 01:57 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Login/CustomView/SocialLoginButton.swift
>          }
@ChoiysApple 
네 아래 코멘트에 작성한것처럼 런타임크래시 유발할 수 있다고 판단해 디폴트 AttributedString을 리턴할까 생각했는데 이는 애초에 자간 및 줄높이가 적용되지않은 텍스트라 생각해서 attribute가 적용되지않은 경우는 fatalError가 맞다고 판단했습니다 !

2024-07-17 11:21 UTC, ChoiysApple approved these changes
수고하셨습니다. 홈화면 빠르게 진행 부탁드려요

2024-07-17 11:21 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Login/CustomView/SocialLoginButton.swift
> +        }
이전 피드백에서 의도했던건 에러를 인지하는 방향보다는, 무언가 잘못되었을때 사용할 수 있는 자원만으로 해당 동작을 충분히 진행하는거였어요. 이 방식은 이런 부분을 해결해주지는 못하네요

사실 이 코드에서 나오는 문제들은, `AttributedText`를 **만드는** 동작과 `AttributedText`를 설정해주는 동작이 분리되지 않아 발생하는 구조적 이슈입니다.

시간이 너무 지체되었고, 리팩토링 예정되어있으니, 이부분은 일단 넘어가는 걸로 할게요

2024-07-17 11:21 UTC, merged

2024-07-17 11:39 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Login/CustomView/SocialLoginButton.swift
> +        }
아 뭔가 제가 UIButton.Configuration에 attribute를 적용시키는 방법을 잘못 작성한걸까요 ??
대건님이 만들어주신 버튼에 attribute적용하는 함수보면서 공부해보는 시간을 가져볼게요

2024-07-17 11:42 UTC, dlrjswns commented
@ChoiysApple 
오늘 스터디만 끝나고 밤새서 홈 부분 PR올리겠습니다, 항상 제 PR에 시간써주셔서 감사해요 👍