[Feature][OMLK-43] 홈 화면관련 UI 구현
YAPP-Github/24th-App-Team-3-iOS pull request #62
Opened 2024-07-15 16:16 UTC by dlrjswns

## Describe

- 홈에 관련된 UI 구현
- 홈 `상단 로고 서치바`에 관련된 스크롤에 따른 다른 레이아웃 구현

## Works made

- `장르구독하기`, `아티스트구독하기`, `티켓팅공연정보`, `추천공연정보`관련 셀 및 헤더, 푸터 추가
- `상단 로고 서치바`의 스크롤영역에 따른 다른 레이아웃을 위해 `FeaturedTopView`구현
- `상단 서치바`에 대한 버튼을 위한 `FeaturedSearchButton` 구현 
- 섹션마다 다른 레이아웃을 갖기때문에 `UICompositonalLayout`을 이용하여 구현

## Changes Made

### As-Is

**기존 로직**
- 기존에 작성된 홈 화면에 대한 로직이 없기때문에 내용없음

**스크린샷**
- 기존에 작성된 홈 화면에 대한 로직이 없기때문에 내용없음

### To-BE

**변경 로직**
``` swift
private func createFeatureCollectionViewLayoutSection(type: FeaturedSectionType) -> NSCollectionLayoutSection {
        switch type {
        case .subscribeGenre:
            let groupLayoutSize = NSCollectionLayoutSize(
                widthDimension: .absolute(100),
                heightDimension: .absolute(100)
            )
            
            let itemLayoutSize = NSCollectionLayoutSize(
                widthDimension: .fractionalWidth(1),
                heightDimension: .fractionalHeight(1)
            )
            
            let item = NSCollectionLayoutItem(layoutSize: itemLayoutSize)
            
            let header = NSCollectionLayoutBoundarySupplementaryItem(
                layoutSize: .init(
                    widthDimension: .fractionalWidth(1),
                    heightDimension: .absolute(44)
                ),
                elementKind: UICollectionView.elementKindSectionHeader,
                alignment: .top
            )
            header.contentInsets = .init(top: .zero, leading: .zero, bottom: .zero, trailing: -7)
            
            let group = NSCollectionLayoutGroup.horizontal(
                layoutSize: groupLayoutSize,
                subitems: [item]
            )
            
            let section = NSCollectionLayoutSection(group: group)
            section.contentInsets = .init(top: 8, leading: 16, bottom: 36, trailing: 16)
            section.boundarySupplementaryItems = [header]
            section.orthogonalScrollingBehavior = .continuous
            section.interGroupSpacing = 10
            return section
// ... 생략
```
- `UICompositionalLayout`, `FeaturedSectionType`을 이용해 레이아웃을 구현

**스크린샷**
<img src="https://github.com/user-attachments/assets/b11ca2c6-852b-4c7c-ba98-2e96e18299ef" width="25%" alt="Image"><img src="https://github.com/user-attachments/assets/70666037-eabc-4403-a136-f6859bded69a" width="25%" alt="Image">

## How to Test

- Featured에 해당하는 화면의 UI를 확인
- 스크롤 시 `FeaturedTopView`에 해당하는 레이아웃이 변경되는 부분을 확인

## Issues Resolved
- #53 

## Additional context

1. `FeaturedTopView`에 관련해서 스크롤에 따른 레이아웃을 `isScrollUp`상태값을 가지고 구현하고있는데 생각보다 어려워 이 부분을 어떻게 구현하면 좋을지 아이디어를 얻고싶습니다.[하단 영상 참고]
https://github.com/user-attachments/assets/5182d24a-1138-4f74-b634-aad9d5c72c82

2. `FeaturedTopView`에 올바른 `isScrollUp`상태값을 넘겨주기위해서 FeaturedViewModel에서 가공해 넘겨주는데 
``` swift
let featuredScrollView = viewHolder.featuredCollectionView
        
let pointObservable = featuredScrollView.rx.didScroll
    .map { featuredScrollView.panGestureRecognizer.translation(in: featuredScrollView.superview) }
        
let input = FeaturedViewModel.Input.panGesturePointWhenScrollFeaturedCollectionView(pointObservable: pointObservable)
        
let output = viewModel.transform(input: input)
        
output.isFeaturedCollectionViewScrollUp
    .drive(viewHolder.featuredTopView.rx.isScrollUp)
    .disposed(by: disposeBag)
```
위 코드와 같이 `input`에 대한 처리가 이게 최선인지 궁금해요, 기존에 `didScroll Delegate`함수내부에서 이를 위 로직을 처리해주었는데 그렇게하니까 함수호출하고 사라져서 `FeaturedViewModel`내부 `distinctUntilChanged`연산자가 동작을 안하게되어 `viewDidLoad`함수내부에서 이를 처리하기위해 저리 변경하였습니다

## References

[스크롤에 따른 상단로고서치바 레이아웃](https://discord.com/channels/1241701172532744202/1255011164249784340/1258437979731398738)
[홈 화면관련 피그마 링크](https://www.figma.com/design/KezpnXlqYPKL39yfOAn4FJ/%EB%94%94%EC%9E%90%EC%9D%B8-%EC%9E%91%EC%97%85%EC%9A%A9?node-id=493-9317&t=sx2bukeAd9745guW-4)
[UICompositionalLayout 공식문서](https://developer.apple.com/documentation/uikit/uicollectionviewcompositionallayout)

2024-07-15 16:18 UTC, dlrjswns commented
@ChoiysApple 
Additional context에 작성하였는데 2가지 부분 혹시 괜찮은 아이디어가 있으실까요 ??
2번을 개발하면서 ViewModelType에 값을 넘기기가 까다롭더라구요, 이 부분도 자문을 구하고싶습니다.

2024-07-16 11:30 UTC, ChoiysApple commented
@dlrjswns 
기존 PR 먼저 빠르게 완료해주세요~

2024-07-17 13:36 UTC, ChoiysApple commented
> @ChoiysApple Additional context에 작성하였는데 2가지 부분 혹시 괜찮은 아이디어가 있으실까요 ?? 2번을 개발하면서 ViewModelType에 값을 넘기기가 까다롭더라구요, 이 부분도 자문을 구하고싶습니다.

일단 코드 양이 많아서 오늘 당장은 피드백 못드릴거 같긴 한데, 동영상 첨부해주신거에서 궁금한게 있어요
아래로 스크롤할 때 아무런 애니메이션 없이 그냥 사라지는것 같은데, 동영상 프레임때문인가요? 아니라면 애니메이션 구현 필요할것 같아요

2024-07-17 13:41 UTC, ChoiysApple commented
건준님 부탁드릴게 있어요
1. 링크 첨부하실때 마크다운 이용해서 달아주시는건 좋습니다. 근데 그냥 줄글이라 보기가 힘들어서 되도록이면 bullet list로 정리해주세요
2. 저번에 문서에 디코 스레드 링크 첨부하지 말고, 요약해서 적으라고 말씀드렸는데 이전 커밋에 스레드 링크 첨부하신게 남아있는거 같네요. 이부분도 되도록이면 정리해주세요. (대화의 결론만 적거나 사양서 등의 문서를 첨부하는걸로 바꿔주세요)
저번에도 말씀드렸지만 다른 사람 보라고 쓰는 글들인데, 논의 과정이 모두 담긴 대화록을 첨부하는건 상당히 좋지 않아요

2024-07-17 13:50 UTC, dlrjswns commented
> > @ChoiysApple Additional context에 작성하였는데 2가지 부분 혹시 괜찮은 아이디어가 있으실까요 ?? 2번을 개발하면서 ViewModelType에 값을 넘기기가 까다롭더라구요, 이 부분도 자문을 구하고싶습니다.
> 
> 일단 코드 양이 많아서 오늘 당장은 피드백 못드릴거 같긴 한데, 동영상 첨부해주신거에서 궁금한게 있어요 아래로 스크롤할 때 아무런 애니메이션 없이 그냥 사라지는것 같은데, 동영상 프레임때문인가요? 아니라면 애니메이션 구현 필요할것 같아요

아 저 부분 안드로이드에 맞춰서 수정하고 올려드리겠습니다 !!

2024-07-17 13:51 UTC, ChoiysApple commented
> > > @ChoiysApple Additional context에 작성하였는데 2가지 부분 혹시 괜찮은 아이디어가 있으실까요 ?? 2번을 개발하면서 ViewModelType에 값을 넘기기가 까다롭더라구요, 이 부분도 자문을 구하고싶습니다.
> 
> > 
> 
> > 일단 코드 양이 많아서 오늘 당장은 피드백 못드릴거 같긴 한데, 동영상 첨부해주신거에서 궁금한게 있어요 아래로 스크롤할 때 아무런 애니메이션 없이 그냥 사라지는것 같은데, 동영상 프레임때문인가요? 아니라면 애니메이션 구현 필요할것 같아요
> 
> 
> 
> 아 저 부분 안드로이드에 맞춰서 수정하고 올려드리겠습니다 !!

? 애니메이션 없는거라구요?

2024-07-17 13:56 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/FeaturedTopView.swift
> +}
@ChoiysApple 
이 부분이 해당 스크롤할때 로직인데 아직 애니메이션이 적용되지않은 상태입니다.
높이를 업데이트하는것으로 구현할 수 있을꺼같은데 아이디어 떠오르지않아 자문을 드렸습니다

2024-07-17 13:57 UTC, dlrjswns commented
> 건준님 부탁드릴게 있어요
> 
> 1. 링크 첨부하실때 마크다운 이용해서 달아주시는건 좋습니다. 근데 그냥 줄글이라 보기가 힘들어서 되도록이면 bullet list로 정리해주세요
> 2. 저번에 문서에 디코 스레드 링크 첨부하지 말고, 요약해서 적으라고 말씀드렸는데 이전 커밋에 스레드 링크 첨부하신게 남아있는거 같네요. 이부분도 되도록이면 정리해주세요. (대화의 결론만 적거나 사양서 등의 문서를 첨부하는걸로 바꿔주세요)
>    저번에도 말씀드렸지만 다른 사람 보라고 쓰는 글들인데, 논의 과정이 모두 담긴 대화록을 첨부하는건 상당히 좋지 않아요

1번 바로 수정하였고 2번도 안드로이드 부분에 맞추면서 푸시할때 커밋내역에서 스레드링크대신에 결과에 대한 내용만 적어놓겠습니다 !!

2024-07-17 14:07 UTC, dlrjswns commented
> > 건준님 부탁드릴게 있어요
> > 
> > 1. 링크 첨부하실때 마크다운 이용해서 달아주시는건 좋습니다. 근데 그냥 줄글이라 보기가 힘들어서 되도록이면 bullet list로 정리해주세요
> > 2. 저번에 문서에 디코 스레드 링크 첨부하지 말고, 요약해서 적으라고 말씀드렸는데 이전 커밋에 스레드 링크 첨부하신게 남아있는거 같네요. 이부분도 되도록이면 정리해주세요. (대화의 결론만 적거나 사양서 등의 문서를 첨부하는걸로 바꿔주세요)
> >    저번에도 말씀드렸지만 다른 사람 보라고 쓰는 글들인데, 논의 과정이 모두 담긴 대화록을 첨부하는건 상당히 좋지 않아요
> 
> 1번 바로 수정하였고 2번도 안드로이드 부분에 맞추면서 푸시할때 커밋내역에서 스레드링크대신에 결과에 대한 내용만 적어놓겠습니다 !!

2024-07-17 14:09 UTC, dlrjswns commented
@ChoiysApple 
안드로이드 작업물과 동일하게 맞추어 푸시하였습니다, 이제 좀 보기 편하실꺼같아요 !

2024-07-17 14:10 UTC, ChoiysApple commented
> @ChoiysApple 
> 
> 안드로이드 작업물과 동일하게 맞추어 푸시하였습니다, 이제 좀 보기 편하실꺼같아요 !

건준님 안드로이드랑 어떤게 달랐는지 전 몰라요...

2024-07-17 14:13 UTC, dlrjswns commented
> > @ChoiysApple
> > 안드로이드 작업물과 동일하게 맞추어 푸시하였습니다, 이제 좀 보기 편하실꺼같아요 !
> 
> 건준님 안드로이드랑 어떤게 달랐는지 전 몰라요...

아 그 부분은 이전 PR에서 홈 UI 전체적으로 개발해서 올렸었는데 로고서치바 + 장르구독 + 아티스트구독까지만 존재하는 화면으로 올려놓았습니다.
riido에 OMLK-43부분에 있는 화면이라고 생각하시면 편할꺼같습니다 !

2024-07-20 08:00 UTC, ChoiysApple requested changes
1. 상단 삭제 (코드는 따로 주세요)
2. 구독중/구독중 아님 상태 따라서 UI 개발
3. 리뷰 반영해서 다시 작업 할것 하기
4. mock 데이터 넣어서 개발

2024-07-21 03:08 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedViewHolder.swift
> +        $0.contentInset = .init(top: .zero, left: .zero, bottom: 103, right: .zero)
@dlrjswns 
건준님 이 103어디에 나와있는 수치인강?

2024-07-21 05:19 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedViewHolder.swift
> +        $0.contentInset = .init(top: .zero, left: .zero, bottom: 103, right: .zero)
아 저거 Featured화면 하단 여백이 103이라서 넣어놨어요

2024-07-21 05:20 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/FeaturedSubscribeArtistCell.swift
> +        artistNameLabel.lineBreakMode = .byTruncatingTail
이 부분 달아놓았습니다 !!

2024-07-21 05:22 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedViewHolder.swift
> +            $0.height.equalTo(1085 + 44) // 장르버튼, 탭바 간격 + 장르버튼 높이
높이관련해서는 상단로고외에것만 하는걸로 이야기돼 추후 완료해주시면 확인하도록 하겠습니다 !

2024-07-21 05:22 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/FeaturedTopView.swift
> +            $0.width.equalTo(91)
이 부분도 위와 동일합니다 !

2024-07-21 05:22 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedViewHolder.swift
> +    private func createFeatureCollectionViewLayoutSection(type: FeaturedSectionType) -> NSCollectionLayoutSection {
넵 이 부분 개발완료하였습니다 !!

2024-07-21 05:22 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedViewModel.swift
> +    enum Input {
`enum` ->`struct`로 수정해서 개발완료하였습니다 !

2024-07-21 05:23 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedViewController.swift
> +        let type = FeaturedSectionType.allCases[indexPath.section]
넵 이 부분도 `ViewModel`에서 섹션순서를 관리할 수 있도록 개발완료하였습니다 !

2024-07-21 05:23 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedViewController.swift
> +            return cell
이 부분 `ViewModel`에서 처리하도록 수정하였습니다 !!

2024-07-21 05:24 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedViewController.swift
> +        let input = FeaturedViewModel.Input.panGesturePointWhenScrollFeaturedCollectionView(pointObservable: pointObservable)
일단 이 부분 상단로고서치바외에것만 개발하기로하여 지워놨습니다 !

2024-07-21 05:25 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedViewController.swift
> +        view.backgroundColor = .gray700 // TODO: - 추후 BaseViewController로 공통 백그라운드 색상 적용
이슈생성완료하였습니다 ! 홈 PR완료되면은 바로 진행하도록 하겠습니다 :)

2024-07-22 14:59 UTC, ChoiysApple requested changes
터치 이벤트까지 작업해서 다시 올려주세요

2024-07-22 14:59 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedViewController.swift
> +            didTappedSearchButton: .just(()), // TODO: - 상단 서치바완성되면 연동 필요
현재 미구현 기능이라 이렇게 해둔건가요?
미구현 기능이라면 `Input`에서 제외하고 `// TODO` 추가하는게 보기 좋을 것 같습니다.

2024-07-22 14:59 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedCoordinator.swift
> +    }
`TODO` 달아두신거 좋아요~
다만 이 메소드까지 동작하는지 확인하기 위해서 로그를 추가해두는게 좋을 것 같아요

2024-07-22 14:59 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedViewHolder.swift
> +        $0.contentInset = .init(top: .zero, left: .zero, bottom: 103, right: .zero)
디자이너분들께 문의드렸는데, 답변 오면 수정해주세요

2024-07-22 14:59 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedViewHolder.swift
> +            )
이부분 너무 길고, 추후에 Use Case로 분리해야 합니다.

별도 메서드나 프로퍼티로 분리해주세요

2024-07-22 14:59 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedViewHolder.swift
> +        }
위와 동일합니다

2024-07-22 14:59 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedViewHolder.swift
> +    }}
괄호 두개 겹쳐있어요
들여쓰기 해주세요

2024-07-22 14:59 UTC, ChoiysApple commented on ShowPot/ShowPot/Resource/Localizable/Localizable.strings
미사용 문구 제거해주세요

2024-07-22 14:59 UTC, ChoiysApple commented on ShowPot/ShowPot/Resource/Localizable/Localizable.strings
> +"home_subscribeArtist_title" = "아티스트 구독하기";
snake case 네이밍 컨벤션 맞춰주세요

2024-07-22 14:59 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedCoordinator.swift
> +    }
그리고 코디네이터에서 하는 **동작** 기준으로 메서드 이름을 정하는게 좋을 것 같아요

코디네이터를 사용하는 코드에서
```swift
input.didTappedSubscribeGenreButton
            .subscribe(with: self) { owner, _ in
                owner.coordinator.goToSubscribeGenrePage()
            }
            .disposed(by: disposeBag)
```

이런식으로 뷰의 동작을 이름으로 하는 것 보단

```swift
**input.didTappedSubscribeGenreButton
            .subscribe(with: self) { owner, _ in
                owner.coordinator.didTappedSubscribeGenreButton()
            }
            .disposed(by: disposeBag)
```
이런식으로 코디네이터에서 직접적으로 어떤 일을 하는지 보여주는게 이해하기 쉬울 거 같아요

2024-07-22 14:59 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedViewModel.swift
> +        let featuredSectionModel = Observable.zip(
zip 사용시, 한가지 리스트만 업데이트 될 경우 두 리스트 모두 동작하지 않을것 같습니다

2024-07-22 14:59 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/FeaturedWithButtonHeaderView.swift
> +    }
viewcontroller에서 직접 rx로 바인딩하면 delegate 사용하지 않고 구현 가능하지 않을까요?

2024-07-22 14:59 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/FeaturedWithButtonHeaderView.swift
> +    }
`FeaturedSectionType`을 사용하지 않는 메서드도 만들어주세요
의존하는 자료형이 변경될 경우 힘들어집니다

2024-07-22 14:59 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedViewModel.swift
> +    private func fetchFeaturedModel() {
1. 장르 목록과 아티스트 목록은 별개의 DB 또는 API를 사용해서 불러옵니다. 별개의 메서드에서 각각의 데이터를 불러와야 합니다.

2. 서버 이미지 url은 없지만, 테스트 과정에서 인터넷에 있는 url을 가져와 테스트해주세요

2024-07-22 14:59 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/FeaturedSubscribeGenreCell.swift
> +        $0.backgroundColor = .red
테스트용 코드에는 `TODO` 또는 `FIXME` 달아주세요

2024-07-22 14:59 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/FeaturedSubscribeGenreCell.swift
> +}
이미지 URL 프로퍼티 하나만 사용하는 상황인데, Struct를 만들어야 할 이유가 있나요?

2024-07-22 14:59 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/FeaturedSubscribeArtistCell.swift
> +    }
Cell Model에 의존적이지 않은 메서드도 만들어주세요

2024-07-22 14:59 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/FeaturedSubscribeArtistCell.swift
> +    private let artistNameLabel = UILabel().then {
truncate 관련 설정도 명시해주세요

2024-07-22 14:59 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/FeaturedSubscribeArtistCell.swift
> +        let isContain = artistImageView.contains(alphaView) && artistImageView.contains(alertImageView)
현재 state에 따라 구분하는 것 이 좋을 것 같습니다

2024-07-22 15:12 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedViewController.swift
> +        }
음 저 부분을 구독할때에 추가해줘도 되지만 말그대로 데이터바인딩작업만 rx로 하는게 맞다 생각했어요, 대건님 말씀처럼 구독하는 부분에서 저 코드를 삽입해도 문제없습니다 !

해당 데이터는 ViewModel에서 관리하고있습니다, 다만 컬렉션뷰를 구성하는데 전역프로퍼티로 섹션모델을 작업해야 사용할 수 있어 전역프로퍼티로 빼놓았습니다.

2024-07-22 15:14 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedCoordinator.swift
> +    }
오 그러네요 로그를 활용해서 추가하도록 하겠습니다 !! 
coordinator부분도 화면흐름에 맞는 네이밍으로 수정하도록 할게요 👍

2024-07-22 15:17 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/FeaturedSubscribeGenreCell.swift
> +}
아 이 부분은 현재 모델에 대한 데이터가 하나만 있지만 추후에 모델을 추가할때에 작업하기 편할 수 있도록 저리 작업하였습니다, 만들어둔 모델에 프로퍼티만 추가하면 컴파일타임때 캐치해서 수정하기도 용이하다고 판단했어요

2024-07-22 15:18 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/FeaturedSubscribeArtistCell.swift
> +    private let artistNameLabel = UILabel().then {
어 이 부분은 FeaturedSubscribeArtistCell의 configureUI함수에서 artistNameLabel을 작업하는 부분에 TODO명시해놓았습니다 !

2024-07-22 15:23 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedViewModel.swift
> +        let featuredSectionModel = Observable.zip(
아 홈에 대한 데이터는 한번 호출할때 묶어서 한번에 바인딩하는 로직이라 생각했는데 그런 상황에 대한 부분도 염두해둬야겠네요
zip -> combineLatest로 수정해놓겠습니다 👍

2024-07-22 15:24 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/FeaturedWithButtonHeaderView.swift
> +    }
오오 해당 모델에 대한 데이터를 만들어서 변경해볼게요

2024-07-22 16:18 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedViewController.swift
> +        }
@ChoiysApple 
대건님 요거 좀 찾아봤는데 UICollectionViewDiffableDataSource를 사용하면 Output을 통해서 바인딩시킬 수 있을꺼같아보이긴한데 대건님은 어떻게 섹션모델을 관리하려고 하셨나요 ??

2024-07-22 17:40 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/FeaturedWithButtonHeaderView.swift
> +    }
ViewController dataSource에서 헤더뷰생성하는곳에서 저 부분을 rx바인딩하라는 말씀이시죠 ? 
저 부분때문에 부수적으로 추가한 부분이 있었는데 그렇게하면 코드를 많이 줄일 수 있을꺼같네요 수정해보겠습니다 🧐🧐

2024-07-23 07:33 UTC, dlrjswns commented on ShowPot/ShowPot/Resource/Localizable/Localizable.strings
> +"home_subscribeArtist_title" = "아티스트 구독하기";
@ChoiysApple 
저 부분 camel case로 변경해달라는 말씀이시죠 ?

2024-07-23 07:46 UTC, dlrjswns commented
@ChoiysApple 
1. FeatureArtistCell의 state에 따라 처리
2. featuredCollectionView UICompositionalLayout함수로 변형한거 Usecase로 변형하기위해 프로퍼티 혹은 함수로 변경
대건님 위 코드리뷰외에 부분은 적용됐는데 저 2가지에 대해서 이해가 잘 안돼서 혹시 설명해주실 수 있을까요 ?

2024-07-23 14:43 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedViewController.swift
> +        }
> @ChoiysApple 대건님 요거 좀 찾아봤는데 UICollectionViewDiffableDataSource를 사용하면 Output을 통해서 바인딩시킬 수 있을꺼같아보이긴한데 대건님은 어떻게 섹션모델을 관리하려고 하셨나요 ??

`RxCocoa` 사용해서 Relay를 바인딩해주거나, `viewModel.output`에 접근해서 리스트 가져왔을거 같네요
`DiffableDataSource`도 좋은 방법입니다만, 말씀하신 의도처럼 전반적인 이해나 영향도에 대한 고려 없이 지금 당장 안되는걸 해결하기 위해 도입하는 사고방식은 좋지는 않은거 같네요

2024-07-23 14:45 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedViewHolder.swift
> +            )
```swift
let subscribeGenreLayoutSection: NSCollectionLayoutSection
private func subscribeGenreLayoutSection() ->  NSCollectionLayoutSection
```

2024-07-23 14:46 UTC, ChoiysApple commented on ShowPot/ShowPot/Resource/Localizable/Localizable.strings
> +"home_subscribeArtist_title" = "아티스트 구독하기";
아뇨 저희 리소스 원본 네이밍은 모두 `snake case` 쓰고 있으니 맞춰달라는 겁니다
```suggestion
"home_subscribe_genre_title" = "장르 구독하기";
"home_subscribe_artist_title" = "아티스트 구독하기";
```

2024-07-23 14:53 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/FeaturedSubscribeArtistCell.swift
> +        let isContain = artistImageView.contains(alphaView) && artistImageView.contains(alertImageView)
> 음 저 로직이 updateLayoutIfNeeded함수안에서 state에 따라 구분지어 setup해주고있는데 어떤 부분을 구분하면 좋다는 말씀이실까요 ??

네 저런방식을 말한거였어요. 토요일에 단 코멘트가 나중에 올라간거 같네요

2024-07-23 14:57 UTC, ChoiysApple commented
@dlrjswns 
건준님 혹시 지금 사용하는 클린 아키텍쳐나, Input-Output 패턴 사용하는게 너무 어렵나요?
이 구조에 맞추시려고 코드 짜시는게 힘들어보여서요

2024-07-23 15:04 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedViewController.swift
> +        }
아 FeaturedViewModel.sectionModel 이런식으로 말씀이시죠 ? 이게 계속 transform거쳐야한다는 방식으로 생각하다보니까 그런거같네요

2024-07-23 15:12 UTC, dlrjswns commented
> @dlrjswns 건준님 혹시 지금 사용하는 클린 아키텍쳐나, Input-Output 패턴 사용하는게 너무 어렵나요? 이 구조에 맞추시려고 코드 짜시는게 힘들어보여서요

@ChoiysApple 
음 Input-Output패턴이 익숙치않아서 난해한 감은 있는데 점점 익숙해지고있어요

2024-07-25 14:16 UTC, ChoiysApple approved these changes
수고하셨습니다~ 수정할 부분이 있긴한데, 알아서 머지하시면 될거 같아서 일단 승인했어요.

1. Cell 클릭시 구독 화면으로 이동하도록 수정
2. 더미 데이터에 `FIXME` 추가
3. 커밋 늘어난거 `squash`해서 정리하시고
4. 직접 머지하신 다음 브랜치 삭제해주시면 될거같아요

일정상 이유로 이전처럼 엄청 자세하게 리뷰는 못드릴거 같네요 ㅠㅠ
사양 따라서 정상 동작하고, 예외 케이스들 테스트 정상적으로 되면 큰 문제는 없을테니 이후부터는 이것 위주로 리뷰할것 같네요

2024-07-25 14:16 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedCoordinator.swift
> +    }
채팅으로 말씀드린거 처럼 셀 클릭시에도 헤더 클릭과 동일하게 구독화면으로 이동되어야 해서, 
수정 필요할거 같아요

2024-07-25 14:16 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedViewModel.swift
> +        subscribeGenreModelRelay.accept([ // TODO: - 추후 API연동 후 MockData코드 수정
나중에 지울 데이터라서, FIXME 명시해주는게 좋을거같아요

2024-07-26 05:13 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedCoordinator.swift
> +    }
넵 수정완료했습니다 👍

2024-07-26 05:28 UTC, dlrjswns commented
@ChoiysApple 
추가적으로 섹션모델넣어놨고 `전체공연`버튼에 대한 액션도 추가해놓았습니다. 
Linear적용하는건 공통함수로 이슈생성하여 만들도록 하겠습니다 🙋🏻‍♂️

2024-07-26 05:29 UTC, merged

2024-07-26 06:28 UTC, ChoiysApple commented
> @ChoiysApple 추가적으로 섹션모델넣어놨고 `전체공연`버튼에 대한 액션도 추가해놓았습니다. Linear적용하는건 공통함수로 이슈생성하여 만들도록 하겠습니다 🙋🏻‍♂️

Linear가 무슨 작업인가요?

2024-07-26 08:56 UTC, dlrjswns commented
<img width="341" alt="스크린샷 2024-07-26 오후 5 53 15" src="https://github.com/user-attachments/assets/c85ddfb2-f633-452a-8493-9f5dfd63642c">
<img width="225" alt="스크린샷 2024-07-26 오후 5 53 25" src="https://github.com/user-attachments/assets/a807abe3-70e8-48ef-840f-cc291dbeedaa">

@ChoiysApple 
- 피그마상으로 티켓팅 셀 우측에 Linear라는 선형 그라데이션이 추가돼 있어요, 그래서 이를 공통함수로 두면 추후 다른 View에도 쉽게 Linear를 적용할 수 있을꺼같아 말씀드렸어요 !

2024-07-26 08:57 UTC, ChoiysApple commented
> <img width="341" alt="스크린샷 2024-07-26 오후 5 53 15" src="https://github.com/user-attachments/assets/c85ddfb2-f633-452a-8493-9f5dfd63642c">
> 
> <img width="225" alt="스크린샷 2024-07-26 오후 5 53 25" src="https://github.com/user-attachments/assets/a807abe3-70e8-48ef-840f-cc291dbeedaa">
> 
> 
> 
> @ChoiysApple 
> 
> - 피그마상으로 티켓팅 셀 우측에 Linear라는 선형 그라데이션이 추가돼 있어요, 그래서 이를 공통함수로 두면 추후 다른 View에도 쉽게 Linear를 적용할 수 있을꺼같아 말씀드렸어요 !

네 좋아요
다음부턴 이런식으로 자세히 설명해주세요