[Feature] #49 userdefaults 관리 로직 개발
YAPP-Github/24th-App-Team-3-iOS pull request #73
Opened 2024-07-23 14:31 UTC by ChoiysApple

## Describe

- UserDefaults를 사용하기 위한 객체 개발

## Works made

- `UserDefaultsManager` 개발
- `UserDefaultsKey` 열거형 추가

## Changes Made

### To-BE

**변경 로직**
```swift
/// UserDefaults 관리 싱글톤 객체
final class UserDefaultsManager {
    
    static let shared = UserDefaultsManager()
    let userDefaults: UserDefaults?
    
    private init() {
        self.userDefaults = UserDefaults.standard
    }
}

extension UserDefaultsManager {
    
    func remove(for key: UserDefaultsKey) {
        self.userDefaults?.removeObject(forKey: key.value)
        self.userDefaults?.synchronize()
    }
    
    func set<T>(_ object: T, for key: UserDefaultsKey) {
        self.userDefaults?.set(object, forKey: key.value)
        self.userDefaults?.synchronize()
    }
    
    func get<T>(for key: UserDefaultsKey) -> T? {
        let result = self.userDefaults?.object(forKey: key.value) as? T
        return result
    }
    
    func getObject(for key: UserDefaultsKey) -> Any? {
        let result = self.userDefaults?.object(forKey: key.value)
        return result
    }
}
```
```swift
/// UserDefults에 사용할 Key값을 관리하기 위한 enum
enum UserDefaultsKey: String {
    /// 최초 실행 여부
    case firstLaunch
    
    var value: String {
        return self.rawValue
    }
}
```
### 고정 변수 대신 `UserDefaults`에서 값을 가져와 판단하도록 수정
```swift
extension MainTabController {
    private func isFirstLaunch() -> Bool {
        
        if let isFirstLaunch: Bool = UserDefaultsManager.shared.get(for: .firstLaunch) {
            return isFirstLaunch
        }
        
        return true // 저장된 값이 없으면 최초 실행
    }
}

extension OnboardingCoordinator {
    func dismiss() {
        if let modal = modalViewController {
            modal.dismiss(animated: true)
            parentCoordinator?.removeChildCoordinator(child: self)
            
            UserDefaultsManager.shared.set(false, for: .firstLaunch)
        }
    }
}
```

## How to Test
- 온보딩 화면 dismiss 이후 다시 표출 안되는지 확인

## Issues Resolved
- #49 

## References

- [UserDefaultsManager is a manager and wrapper class for UserDefaults](https://gist.github.com/amrangry/6920e74fc50bad3e2f2c213a28403b5f)

2024-07-23 14:59 UTC, dlrjswns requested changes

2024-07-23 14:59 UTC, dlrjswns commented on ShowPot/ShowPot/Data/UserDefaults/UserDefaultsManager.swift
> +    let userDefaults: UserDefaults?
UserDefaults.standard는 항상 값을 반환하는것으로 알고있는데 옵셔널로 선언한 이유가 궁금해요 !

2024-07-23 14:59 UTC, dlrjswns commented on ShowPot/ShowPot/Data/UserDefaults/UserDefaultsManager.swift
> +    }
[synchronize 공식문서](https://developer.apple.com/documentation/foundation/userdefaults/1414005-synchronize)
이 synchronize는 공식문서에서도 불필요하다고 말하는걸보면 삭제해도 좋을꺼같습니다 !

2024-07-23 14:59 UTC, dlrjswns commented on ShowPot/ShowPot/Data/UserDefaults/UserDefaultsManager.swift
> +    }
위 두 함수의 차이가 뭔지 궁금해요 !

2024-07-23 15:11 UTC, ChoiysApple commented on ShowPot/ShowPot/Data/UserDefaults/UserDefaultsManager.swift
> +    let userDefaults: UserDefaults?
여기서는 `standard`를 사용하고 있지만, 이를 사용하지 않고 커스텀으로 생성해서 사용할 수 있어요:[init()](https://developer.apple.com/documentation/foundation/userdefaults/1414356-init) 

만약 커스텀 UserDefault를 사용하게 될 경우(그럴 일은 없겠다만)를 대비하여 옵셔널로 남겨두었어요

2024-07-23 15:12 UTC, ChoiysApple commented on ShowPot/ShowPot/Data/UserDefaults/UserDefaultsManager.swift
> +    }
원래 커스텀 객체관련 코드에 사용되는 메서드인데, stash 올리는 과정에서 약간 꼬여서 안올라갔네요
커스텀 객체 올리는 코드 같이 올려서 업데이트할게요

2024-07-23 15:30 UTC, dlrjswns commented on ShowPot/ShowPot/Data/UserDefaults/UserDefaultsManager.swift
> +    }
넵 확인했습니다 👍

2024-07-24 11:34 UTC, dlrjswns approved these changes
수고많으셨습니다 대건님

2024-07-24 11:53 UTC, merged