[Feature] #67 검색화면 구현 및 로직 작성
YAPP-Github/24th-App-Team-3-iOS pull request #91
Opened 2024-07-29 18:06 UTC by dlrjswns

## Describe

- 검색화면 및 검색결과에 대한 화면 로직을 구현

## Works made

- 최근 검색 특성상 잦은 데이터 변경이 존재하기때문에 `DiffableDataSource`를 적용해 애니메이션을 통해 구성하였습니다
- 텍스트 수에 따른 `returnKey` 적용 -> 텍스트가 존재한다면 `search` 존재하지않다면 `default`
- 텍스트가 비어있는 경우 `검색결과` -> `최근검색` 화면 이동
- 현재 화면에 따른 백버튼 로직 적용
1. 최근검색리스트인 경우 -> `홈화면`으로 pop
2. 검색결과화면인 경우 -> `최근검색리스트`로 이동
- 검색에 따른 `인디케이터` 적용
- 스와이프 및 탭에 따른 `resignResponder` 적용
- 검색결과 아티스트 셀 선택 시 레이아웃 변경 적용
- 검색결과 아티스트만 존재 시 레이아웃 적용
- 최근 검색 데이터가 존재여부에 따라 `emptyLabel` 적용
- 최근검색 좌측정렬을 위한 `LeftAlignedCollectionViewFlowLayout` 추가
- 최근 검색 데이터 `최대갯수 7개` 적용
- 최근 검색 최대 길이 `디바이스 너비-32` 적용

## Changes Made

### As-Is

**기존 로직**
- 이전 작업한 검색화면이 없음

**스크린샷**
- 이전 작업한 검색화면이 없음

### To-BE

**변경 로직**

**스크린샷**
<img src="https://github.com/user-attachments/assets/268086ae-b3d0-44e4-8853-ad8f2bc0f68b" width="25%" alt="Image"><img src="https://github.com/user-attachments/assets/aca772eb-7dd5-4c40-a265-73aaa8bd3e1e" width="25%" alt="Image"><img src="https://github.com/user-attachments/assets/fdd13523-563a-44f5-ba5c-584668b73d35" width="25%" alt="Image"><img src="https://github.com/user-attachments/assets/64524e86-6a57-4b10-8f75-294d901047fa" width="25%" alt="Image">

## How to Test

``` swift
let navigationController = UINavigationController()
window.rootViewController = navigationController
let coordinator = FeaturedSearchCoordinator(navigationController: navigationController)
coordinator.start()
```
- 위 코드를 통해 검색화면 확인 
- FeaturedSearchTextField를 통해 검색 혹은 버튼에 따른 로직 확인 
- 검색결과 아티스트 셀 클릭에 따른 레이아웃 변경 확인

## Issues Resolved

- #67 

## Additional context

- 아티스트 구독 성공 시 레이아웃 변경 및 스낵바 적용은 API연동 이후 구현

## References

[최근검색리스트 레이아웃](https://apple-apeach.tistory.com/74)
[DiffableDataSource MVVM](https://medium.com/swlh/creating-a-reusable-uicollectionviewdiffabledatasource-object-using-mvvm-434976a1dfee)
[검색바 참고자료](https://ios-development.tistory.com/625)

2024-07-30 12:40 UTC, ChoiysApple requested changes
리뷰 남긴거 수정해주시고

1. 아티스트 리스트쪽 Cell 상태관리가 정상적으로 안되는것 같습니다. UI 상으로 구독상태까진 되는데,  그 이후 인터렉션이 안되요
2. 아티스트 리스트 Cell 터치시 로그 남길 수 있도록 해주세요. 
3. 아티스트 / 공연 정보 리스트 로그 남기실 때, 그냥 눌럿다만 나오는게 아니라 해당 Cell을 구별할 수 있다는게 테스트가 되어야합니다. 해당 Cell의 정보를 같이 표출해주세요(이걸 테스트하려면 테스트데이터가 지금처럼 다 같은데이터이면 안됩니다)

2024-07-30 12:40 UTC, ChoiysApple commented on ShowPot/ShowPot/Resource/Localizable/Localizable.strings
> +"search_query_button_title" = "모두삭제";
여기도 query 보단 keyword 같은 네이밍이 좋을 것 같습ㄴ니다

2024-07-30 12:40 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/FeaturedSubscribeArtistCell.swift
> +    }
`UUID`가 있어서 필요 없지 않나요?

2024-07-30 13:08 UTC, dlrjswns commented on ShowPot/ShowPot/Common/UI/LeftAlignedCollectionViewFlowLayout.swift
@ChoiysApple 
아 이게 develop브랜치에서 Layout폴더가 사라지게되면서 develop을 rebase이후 저 부분이 실수로 사라져서 xcode `Compile Source`에서 삭제하고 다시 넣었습니다 !

아 한번 수정해보도록 하겠습니다 👍

2024-07-30 13:13 UTC, dlrjswns commented on ShowPot/ShowPot/Resource/Localizable/Localizable.strings
> +"search_query_button_title" = "모두삭제";
@ChoiysApple 
확인했습니다 ! query대신 keyword와 같은 네이밍으로 수정하도록 할게요 !

2024-07-30 13:16 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/FeaturedSubscribeArtistCell.swift
> +    }
@ChoiysApple 
맞아요 ! 굳이 저 함수를 작성하지않아도 알아서 인지해요
그러나 uuid를 사용하지않고 이후 해당 모델에 대한 id로 대체 해야하기에 저 부분을 작성해놓았어요 !

2024-07-30 13:19 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Search/CustomView/FeaturedRecentSearchCell.swift
> +    private let xButton = UIButton().then {
@ChoiysApple 
아 네이밍을 좀 더 고민해볼게요 !
xbutton사이즈는 피그마에서 24로 고정해놓은거라 어쩔 수 없는 부분인거같아요 !

2024-07-30 13:22 UTC, dlrjswns commented
> 리뷰 남긴거 수정해주시고
> 
> 1. 아티스트 리스트쪽 Cell 상태관리가 정상적으로 안되는것 같습니다. UI 상으로 구독상태까진 되는데,  그 이후 인터렉션이 안되요
> 2. 아티스트 리스트 Cell 터치시 로그 남길 수 있도록 해주세요.
> 3. 아티스트 / 공연 정보 리스트 로그 남기실 때, 그냥 눌럿다만 나오는게 아니라 해당 Cell을 구별할 수 있다는게 테스트가 되어야합니다. 해당 Cell의 정보를 같이 표출해주세요(이걸 테스트하려면 테스트데이터가 지금처럼 다 같은데이터이면 안됩니다)

@ChoiysApple 
2, 3번 관련해서 섹션마다 다른 로그를 찍힐 수 있도록 수정할게요 !
1번에서는 일부로 구독상태된 셀은 터치하지못하도록 하였어요, 그 이유는 구독 이후에 추가적인 인터렉션에 의한 동작이 필요없기 때문인데 이 부분도 일단 구독상태더라도 현재 터치된 셀에 대한 정보를 찍어두도록 할게요

2024-07-30 14:11 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Search/CustomView/FeaturedRecentSearchCell.swift
> +    private let xButton = UIButton().then {
아뇨 텍스트 "x" 말한거에요

2024-07-30 14:12 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Search/CustomView/FeaturedRecentSearchHeaderView.swift
> +    private let removeAllButton = UIButton().then { // TODO: - attribute적용 이후 텍스트가 안보이는 문제 해결 필요
@dlrjswns 
이거 확인하고 답변부탁드려요

2024-07-30 15:01 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Search/CustomView/FeaturedRecentSearchHeaderView.swift
> +    private let removeAllButton = UIButton().then { // TODO: - attribute적용 이후 텍스트가 안보이는 문제 해결 필요
@ChoiysApple 
아 이게 태그를 안걸면 알림이 안뜨네요, 그 저 버튼에서 titleLabel을 이용해서 setAttributedText를 적용하게되면은 기존에 보였던 `모두 삭제` 버튼이 안보이더라구요

그래서 일단은 TODO로 명시해두었습니다

2024-07-30 15:14 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Search/CustomView/FeaturedSearchTextField.swift
> +    private func updateReturnKey(type: UIReturnKeyType) {
@ChoiysApple 
텍스트필드에 키워드가 존재하지않을 경우 returnKeyType이 default, 존재한다면 search로 타입을 변경해야해요

그래서 returnKeyType을 변경할때에 반드시 reloadInputViews를 호출해야하기에 이를 함수로 구현해두었어요

2024-07-30 15:17 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Search/CustomView/FeaturedSearchTextField.swift
> +    var didTappedReturnButton: Observable<String> {
ReturnKey라고 정정하겠습니다 !

2024-08-01 16:18 UTC, ChoiysApple approved these changes

2024-08-01 16:18 UTC, ChoiysApple commented
@dlrjswns 
커밋 정리 후 머지해주세요

2024-08-01 16:52 UTC, merged