[Feature] #79 Linear Gradient 적용을 위한 공통 함수
YAPP-Github/24th-App-Team-3-iOS pull request #92
Opened 2024-07-30 13:04 UTC by dlrjswns

## Describe

- Linear Gradient를 적용할 수 있는 공통 함수 생성 
- 홈화면 티켓팅 셀에 Linear Gradient 적용
- 홈화면 티켓팅 관련 네이밍 경고 수정

## Works made

- 티켓팅 셀에 공연이미지에 적용하기위해 Linear Gradient를 적용하는 함수를 생성 
- UIView의 bounds값을 제때 가져오지못해 적용되지않은 문제로 layoutSubviews에 사이즈 업데이트를 위한 함수 추가

## Changes Made

### As-Is

**기존 로직**
- 기존 Linear Gradient가 적용되지않아 텍스트가 겹침(Linear Gradient관련해서 작성된 코드X)

**스크린샷**
<img src="https://github.com/user-attachments/assets/d4ee4a3d-9841-46e0-9fa5-2f2008d41cf5" width="25%" alt="Image">

### To-BE

**변경 로직**
``` swift
performanceBackgroundImageView.applyLinearGradient(
      colors: [
          .gray700.withAlphaComponent(1.0),
          .gray700.withAlphaComponent(0.3),
          .gray700.withAlphaComponent(0.0)
      ],
      startPoint: .init(x: 0.0, y: 0.5),
      endPoint: .init(x: 1.0, y: 0.5)
)

override func layoutSubviews() {
    super.layoutSubviews()
    performanceBackgroundImageView.updateGradientLayerFrame()
}
```
- `applyLinearGradient`함수를 이용해 원하는 UIView에 적용가능
- `applyLinearGradient`함수 내부에서 bounds값을 통해 적용하지만 적용이 안되는 문제가 있어 `updateGradientLayerFrame`함수를 이용해 사이즈 업데이트하여 올바른 Gradient 적용

**스크린샷**
<img src="https://github.com/user-attachments/assets/ea18f6cc-adc1-483f-adf2-76df19824680" width="25%" alt="Image">

## How to Test

- 홈화면에 `티켓팅공연` 섹션부분에 셀에 올바르게 Linear Gradient가 적용됐는지 확인

## Issues Resolved

- #79 

## Additional context

- 기존 클래스 이름이 다소 길어 티켓팅 셀 관련 SwiftLint 경고문 해당 PR에서 수정하였습니다.

## References

[Linear Gradient 적용방법](https://babbab2.tistory.com/55)
[Linear Gradient적용안되는 문제 해결](https://stackoverflow.com/questions/52348716/gradient-view-not-working-programmatically-with-swift)

2024-07-30 13:22 UTC, ChoiysApple requested changes
코멘트 확인하고 수정해주세요

그리고 저희 디자인이 오른쪽 끝까지 gradient가 적용되는걸로 합의 된 걸로 아는데, 이 사진으로는 확인이 어렵습니다. 디자인 가이드와 동일한 이미지로 테스트하고 디자이너 쪽에 컨펌받아주세요

2024-07-30 13:22 UTC, ChoiysApple commented on ShowPot/ShowPot/Common/Extension/UIView+CALayer.swift
> +    func updateGradientLayerFrame() {
applyLinearGradient 메서드에서 같이 처리해도 되지 않나요?
로직을 분리한 의도가 있나요?

2024-07-30 13:22 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/FeaturedPerformanceTicketingCell.swift
디벨롭에 올라와 있는 변수명이랑 다르지 않나요?
그리고 바꾸실거면 그냥 `FeaturedUpcommingCell` 정도만 해도 괜찮을거 같습니다.

공연 상세 페이지에 티켓팅 관련 정보 뷰가 많을거라 혼동이 있을 수 있어요

2024-07-30 13:50 UTC, dlrjswns commented on ShowPot/ShowPot/Common/Extension/UIView+CALayer.swift
> +    func updateGradientLayerFrame() {
@ChoiysApple 
아 레퍼런스를 참고하시면 현재 함수내부에서 gradient layer의 사이즈를 적용하고있는데 이 부분을 layoutSubviews함수에서 변경된 사이즈를 적용하기위해 해당 함수를 분리하였어요 !

2024-07-30 13:52 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/FeaturedPerformanceTicketingCell.swift
@ChoiysApple 
오 아이디어 감사합니다, `FeaturedUpcommingCell`로 수정하도록 할게요 !

2024-07-30 13:53 UTC, dlrjswns commented
> 코멘트 확인하고 수정해주세요
> 
> 그리고 저희 디자인이 오른쪽 끝까지 gradient가 적용되는걸로 합의 된 걸로 아는데, 이 사진으로는 확인이 어렵습니다. 디자인 가이드와 동일한 이미지로 테스트하고 디자이너 쪽에 컨펌받아주세요

@ChoiysApple 
아 일단 저 사진 그대로 디자인분에게 컨펌받긴했는데 기존 피그마 이미지대로 변경해서 한번 더 컨펌받아볼게요 👍

2024-07-30 17:32 UTC, dlrjswns commented
@ChoiysApple 
요청하신대로 네이밍 변경한 부분 제외하고 올렸고 피그마 이미지를 적용한 화면 디자이너분께 컨펌까지 받았습니다

이미지는 피그마 이미지에서 테스트 URL로 변경 후 푸시했어요

2024-07-31 08:10 UTC, ChoiysApple approved these changes

2024-07-31 08:10 UTC, ChoiysApple commented on ShowPot/ShowPot/Common/Extension/UIView+CALayer.swift
> +    func updateGradientLayerFrame() {
다음부턴 그런 내용들 주석에 적어주세요
"그라디언트 레이어의 프레임을 업데이트하는 함수" 정도의 정보는 함수 메서드명 만으로 충분히 알 수있어요

2024-07-31 08:11 UTC, merged