[Feature] #93 티켓팅 공연 시간정보 칩 UI로 변경
YAPP-Github/24th-App-Team-3-iOS pull request #94
Opened 2024-07-31 08:49 UTC by dlrjswns

## Describe

- 티켓팅정보관련 디자인이 칩 UI로 변경됨에 따라 코드 수정

## Works made

- 기존 티켓팅 시간정보를 단순 텍스트로 작성된 부분을 `PerformanceStateView`를 이용해 칩 UI로 보여줄 수 있도록 구현 

## Changes Made

### As-Is

**기존 로직**
``` swift
private let ticketingOpenTimeLabel = UILabel().then {
    $0.font = ENFont.H5
    $0.textColor = .mainYellow
}

ticketingOpenTimeLabel.setAttributedText(font: ENFont.self, string: model.ticketingOpenTime)
```
- 기존 UILabel에 단순 텍스트를 넣어주었음

**스크린샷**
<img src="https://github.com/user-attachments/assets/d4e31aec-392c-4c9e-b308-5aced9b1d395" width="25%" alt="Image">

### To-BE

**변경 로직**
``` swift
enum PerformanceState {
    case upcoming(String)
    case reserving
    
    var title: String {
        switch self {
        case .upcoming:
            return "오픈예정"
        case .reserving:
            return "예매중"
        }
    }
}
private let performanceStateView = PerformanceStateView()

performanceStateView.configureUI(with: model.perfonmanceState)
```
- `PerformanceStateView`에서 상태값에 따라 칩 UI를 만들어 생성해줌

**스크린샷**
<img src="https://github.com/user-attachments/assets/1809671b-e66c-43ac-af9b-bd1e9927eccd" width="25%" alt="Image">

## How to Test

- 홈 화면에 해당하는 티켓팅정보 셀을 확인하여 올바르게 칩 UI가 보이는지 확인 
- `FeaturedViewModel`의 티켓팅 정보를 넣는 `fetchTicketingPerformanceListModel`함수에서 MockData를 수정하여 올바르게 나오는지 확인

## Issues Resolved

- #93

2024-07-31 14:08 UTC, ChoiysApple requested changes
- #90 
해당 작업 완료된 이후 rebase 해서 적용 완료하시고 다시 리뷰 요청 하시면 될거같아요

2024-07-31 14:08 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/PerformanceStateView.swift
> +    func configureUI(with model: PerformanceState) {
매번 말씀드리지만, 해당 뷰에서만 쓰는 모델 없이 사용하는 configure 메서드 만들어주세요

특히 이런식으로 enum에 종속적으로 개발하면, 표출할 데이터가 하나라도 더 추가되었을때 구조를 싹 갈아야 합니다.

2024-07-31 14:08 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/PerformanceStateView.swift
> +    case upcoming(String)
날짜 정보 때문에 String 연관값으로 두신것 같은데, 이런 식으로 개발하면 나중에 switch로 분기처리가 불가피해집니다. 

enum을 너무 많이 쓰는게 좋은 방법은 아니지만, 현재 상황에선 최선인 것 같으니 아래 `title` 처럼 처리해주세요

그리고 날짜 데이터인데, 무조건 `String`으로 데이터를 받는게 좋은 방법일까요? API 문서 보고 데이터가 어떻게 들어오는지 확인해보면서 생각해보시는게 좋을 것 같습니다.

2024-07-31 14:08 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedViewModel.swift
> +                perfonmanceState: .upcoming("10.10(MON) 11:00"), performanceTitle: "Nothing But Thieves But Thieves ", performanceLocation: "KBS 아레나홀", performanceImageURL: URL(string: "https://media
저번에도 말씀드린 것 같은데, 테스트 데이터 작성하실때 여러가지 다른 데이터로 테스트해주세요.
텍스트 길이나 이미지 크기 등에 따라서 다르게 표출되는 것도 같이 테스트 되어야 합니다.
특히 이미지의 경우는 캐싱이 원하는 대로 동작하는지 테스트도 안되구요

2024-07-31 15:32 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/PerformanceStateView.swift
> +    case upcoming(String)
저희 날짜관련해서 `"ticketingDateTime": "string"` 이렇게 Swagger에 작성되있기도하고 
프론트쪽에서 하지않고 서버쪽에서 매핑된 날짜문자열이 내려오는거 아닌가요 ??

2024-07-31 16:10 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/PerformanceStateView.swift
> +    case upcoming(String)
아 이 부분이 서버쪽에서 매핑된 날짜문자열을 내려보내주기도하고 Swagger에도 문자열로 내려와 1차원적으로 생각한거같습니다 

- #95 해당 이슈를 통해 기존 작업물 이후 리팩토링하여 개선해보도록 할게요

2024-07-31 17:03 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Tab/Featured/FeaturedViewModel.swift
> +                perfonmanceState: .upcoming("10.10(MON) 11:00"), performanceTitle: "Nothing But Thieves But Thieves ", performanceLocation: "KBS 아레나홀", performanceImageURL: URL(string: "https://media
텍스트같은 경우는 전부 테스트해보았고 이미지는 사이즈가 큰것 위주로 넣어 테스트코드 추가하도록 할게요

2024-08-02 16:44 UTC, ChoiysApple requested changes

2024-08-02 16:44 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/FeaturedPerformanceWithTicketOnSaleSoonCell.swift
>          performanceBackgroundImageView.layoutIfNeeded()
건준님 model 사용하는 configure 함수는, model 사용하지 않는 configure 함수를 이용하는게 좋을 것 같습니다.
model을 사용하는 이유가 데이터를 묶어서 한번에 편하게 전달하기 위함인데, base 로직인 `model 미사용 configure` 함수를 사용해서 configure 해 주어야 사양이 틀어지지 않을 것 같네요. 

```swift
func configureUI(with model: FeaturedPerformanceWithTicketOnSaleSoonCellModel) {
         self.configuireUI(
         performanceTitle: model.performanceTitle, 
          ... 
         )
}
```

2024-08-02 16:44 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/PerformanceStateView.swift
> +    case upcoming(Date)
연관값 사용 지양해달라고 피드백 드리지 않았나요?

이 enum은 chip ui 표출 유형을 결정하는 자료형인데,
Date는 서버에서 내려오는 데이터이기 때문에 `FeaturedPerformanceWithTicketOnSaleSoonCellModel`에 들어가야 합니다

2024-08-02 16:44 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/PerformanceStateView.swift
> +        performanceStateView.setText(model.title)
위쪽에서 피드백 드린 `configure` 함수 관련 내용과 동일합니다

2024-08-02 17:20 UTC, dlrjswns commented on ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/PerformanceStateView.swift
> +    case upcoming(Date)
아 연관값을 사용하지말라는데 날짜데이터를 String말고 Date를 쓰라는 의미로 오해했네요, 수정했습니다

2024-08-02 17:59 UTC, ChoiysApple requested changes

2024-08-02 17:59 UTC, ChoiysApple commented on ShowPot/ShowPot/Presentation/Scene/Tab/Featured/CustomView/FeaturedPerformanceWithTicketOnSaleSoonCell.swift
> +        )
이쪽 피드백 안고치셨습니다

2024-08-03 05:35 UTC, ChoiysApple approved these changes

2024-08-03 05:35 UTC, merged